// <auto-generated />
using System;
using System.Text.Json;
using HotelOS.GuestOps.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HotelOS.GuestOps.Infrastructure.Migrations
{
    [DbContext(typeof(GuestOpsDbContext))]
    partial class GuestOpsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("reservations")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HotelOS.GuestOps.Domain.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid?>("AssignedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by");

                    b.Property<int>("Reason")
                        .HasColumnType("integer")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<Guid>("StayId")
                        .HasColumnType("uuid")
                        .HasColumnName("stay_id");

                    b.HasKey("Id")
                        .HasName("pk_assignments");

                    b.HasIndex("StayId")
                        .HasDatabaseName("ix_assignments_stay_id");

                    b.HasIndex("RoomId", "ReleasedAt")
                        .HasDatabaseName("ix_assignments_room_id_released_at");

                    b.ToTable("assignments", "reservations");
                });

            modelBuilder.Entity("HotelOS.GuestOps.Domain.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int?>("ExpectedStayCount")
                        .HasColumnType("integer")
                        .HasColumnName("expected_stay_count");

                    b.Property<bool?>("IsComplete")
                        .HasColumnType("boolean")
                        .HasColumnName("is_complete");

                    b.Property<int>("Origin")
                        .HasColumnType("integer")
                        .HasColumnName("origin");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("PropertyId")
                        .HasDatabaseName("ix_bookings_property_id");

                    b.ToTable("bookings", "reservations");
                });

            modelBuilder.Entity("HotelOS.GuestOps.Domain.BookingExternalRef", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_id");

                    b.Property<string>("IdentifierKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("identifier_kind");

                    b.Property<string>("IntegrationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("integration_id");

                    b.HasKey("Id")
                        .HasName("pk_booking_external_refs");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_booking_external_refs_booking_id");

                    b.HasIndex("IntegrationId", "IdentifierKind", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("uq_booking_external_refs__identity");

                    b.ToTable("booking_external_refs", "reservations");
                });

            modelBuilder.Entity("HotelOS.GuestOps.Domain.CommercialTerms", b =>
                {
                    b.Property<Guid>("StayId")
                        .HasColumnType("uuid")
                        .HasColumnName("stay_id");

                    b.Property<TimeOnly?>("CancelDropTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("cancel_drop_time");

                    b.Property<int?>("CancelOffsetDaysFromArrival")
                        .HasColumnType("integer")
                        .HasColumnName("cancel_offset_days_from_arrival");

                    b.Property<int?>("DepositOffsetDaysFromBooking")
                        .HasColumnType("integer")
                        .HasColumnName("deposit_offset_days_from_booking");

                    b.Property<string>("GuaranteeCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("guarantee_code");

                    b.Property<string>("GuaranteeDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("guarantee_description");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<bool>("OnHold")
                        .HasColumnType("boolean")
                        .HasColumnName("on_hold");

                    b.Property<string>("PenaltyBasis")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("penalty_basis");

                    b.Property<int?>("PenaltyNights")
                        .HasColumnType("integer")
                        .HasColumnName("penalty_nights");

                    b.Property<string>("RateCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("rate_code");

                    b.Property<string>("RateName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("rate_name");

                    b.Property<bool>("ReservesInventory")
                        .HasColumnType("boolean")
                        .HasColumnName("reserves_inventory");

                    b.HasKey("StayId")
                        .HasName("pk_commercial_terms");

                    b.ToTable("commercial_terms", "reservations");
                });

            modelBuilder.Entity("HotelOS.GuestOps.Domain.ContactPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("GuestId")
                        .HasColumnType("uuid")
                        .HasColumnName("guest_id");

                    b.Property<bool?>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<int>("Origin")
                        .HasColumnType("integer")
                        .HasColumnName("origin");

                    b.Property<string>("TechType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tech_type");

                    b.Property<string>("UseType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("use_type");

                    b.Property<byte[]>("ValueCipher")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("value_cipher");

                    b.Property<byte[]>("ValueIndex")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("value_index");

                    b.HasKey("Id")
                        .HasName("pk_contact_points");

                    b.HasIndex("GuestId")
                        .HasDatabaseName("ix_contact_points_guest_id");

                    b.HasIndex("Kind", "ValueIndex")
                        .HasDatabaseName("ix_contact_points__blind_index");

                    b.ToTable("contact_points", "reservations");
                });

            modelBuilder.Entity("HotelOS.GuestOps.Domain.GuestIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("NameAsGiven")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("name_as_given");

                    b.Property<string>("NameFamily")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_family");

                    b.Property<string>("NameGiven")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_given");

                    b.Property<int>("Origin")
                        .HasColumnType("integer")
                        .HasColumnName("origin");

                    b.Property<string>("Preferences")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("preferences");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_guests");

                    b.HasIndex("PropertyId")
                        .HasDatabaseName("ix_guests_property_id");

                    b.ToTable("guests", "reservations");
                });

            modelBuilder.Entity("HotelOS.GuestOps.Domain.Registration", b =>
                {
                    b.Property<Guid>("StayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("stay_id");

                    b.Property<string>("AddressLine")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address_line");

                    b.Property<DateOnly?>("ArrivedInCountryOn")
                        .HasColumnType("date")
                        .HasColumnName("arrived_in_country_on");

                    b.Property<string>("ArrivingFrom")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("arriving_from");

                    b.Property<Guid?>("CapturedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("captured_by");

                    b.Property<string>("CardNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("card_number");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("DocumentRefs")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("document_refs");

                    b.Property<DateOnly?>("IdExpiry")
                        .HasColumnType("date")
                        .HasColumnName("id_expiry");

                    b.Property<string>("IdIssuer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("id_issuer");

                    b.Property<string>("IdNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id_number");

                    b.Property<string>("IdType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id_type");

                    b.Property<string>("NameAsOnId")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("name_as_on_id");

                    b.Property<string>("Nationality")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("nationality");

                    b.Property<DateOnly?>("PassportExpiry")
                        .HasColumnType("date")
                        .HasColumnName("passport_expiry");

                    b.Property<DateOnly?>("PassportIssue")
                        .HasColumnType("date")
                        .HasColumnName("passport_issue");

                    b.Property<string>("PassportNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("passport_number");

                    b.Property<string>("PassportPlace")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("passport_place");

                    b.Property<string>("PortOfArrival")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("port_of_arrival");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("postal_code");

                    b.Property<string>("ProceedingTo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("proceeding_to");

                    b.Property<string>("PurposeOfVisit")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("purpose_of_visit");

                    b.Property<string>("SignatureRef")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("signature_ref");

                    b.Property<DateTimeOffset?>("SignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("signed_at");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("state");

                    b.Property<Guid>("StayId1")
                        .HasColumnType("uuid")
                        .HasColumnName("stay_id1");

                    b.Property<string>("VehicleNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("vehicle_number");

                    b.Property<DateOnly?>("VisaExpiry")
                        .HasColumnType("date")
                        .HasColumnName("visa_expiry");

                    b.Property<DateOnly?>("VisaIssue")
                        .HasColumnType("date")
                        .HasColumnName("visa_issue");

                    b.Property<string>("VisaNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("visa_number");

                    b.Property<string>("VisaType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("visa_type");

                    b.HasKey("StayId")
                        .HasName("pk_registrations");

                    b.HasIndex("CardNumber")
                        .IsUnique()
                        .HasDatabaseName("uq_registrations__card_number")
                        .HasFilter("card_number IS NOT NULL");

                    b.HasIndex("StayId1")
                        .HasDatabaseName("ix_registrations_stay_id1");

                    b.ToTable("registrations", "reservations");
                });

            modelBuilder.Entity("HotelOS.GuestOps.Domain.RoomOutOfOrder", b =>
                {
                    b.Property<Guid>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<DateOnly>("FromDate")
                        .HasColumnType("date")
                        .HasColumnName("from_date");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_type_id");

                    b.Property<DateOnly?>("ToDate")
                        .HasColumnType("date")
                        .HasColumnName("to_date");

                    b.HasKey("RoomId")
                        .HasName("pk_rooms_out_of_order");

                    b.HasIndex("PropertyId", "FromDate", "ToDate")
                        .HasDatabaseName("ix_rooms_out_of_order_property_id_from_date_to_date");

                    b.ToTable("rooms_out_of_order", "reservations");
                });

            modelBuilder.Entity("HotelOS.GuestOps.Domain.RoomStay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateOnly?>("BusinessDate")
                        .HasColumnType("date")
                        .HasColumnName("business_date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("CurrentRoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_room_id");

                    b.Property<int>("Lifecycle")
                        .HasColumnType("integer")
                        .HasColumnName("lifecycle");

                    b.Property<int>("Origin")
                        .HasColumnType("integer")
                        .HasColumnName("origin");

                    b.Property<bool>("PmsUnknown")
                        .HasColumnType("boolean")
                        .HasColumnName("pms_unknown");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_type_id");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<bool>("WalkIn")
                        .HasColumnType("boolean")
                        .HasColumnName("walk_in");

                    b.HasKey("Id")
                        .HasName("pk_room_stays");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_room_stays_booking_id");

                    b.HasIndex("CurrentRoomId")
                        .HasDatabaseName("ix_room_stays_current_room_id");

                    b.HasIndex("PropertyId", "BusinessDate")
                        .HasDatabaseName("ix_room_stays_property_id_business_date");

                    b.HasIndex("PropertyId", "Lifecycle")
                        .HasDatabaseName("ix_room_stays_property_id_lifecycle");

                    b.HasIndex("PropertyId", "RoomTypeId")
                        .HasDatabaseName("ix_room_stays_property_id_room_type_id");

                    b.ToTable("room_stays", "reservations");
                });

            modelBuilder.Entity("HotelOS.GuestOps.Domain.StayAbsence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("field");

                    b.Property<string>("RawValue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("raw_value");

                    b.Property<int>("Reason")
                        .HasColumnType("integer")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("StayId")
                        .HasColumnType("uuid")
                        .HasColumnName("stay_id");

                    b.HasKey("Id")
                        .HasName("pk_stay_absences");

                    b.HasIndex("StayId", "Field")
                        .IsUnique()
                        .HasDatabaseName("uq_stay_absences__field");

                    b.ToTable("stay_absences", "reservations");
                });

            modelBuilder.Entity("HotelOS.GuestOps.Domain.StayDisagreement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Aspect")
                        .HasColumnType("integer")
                        .HasColumnName("aspect");

                    b.Property<DateTimeOffset?>("ClearedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cleared_at");

                    b.Property<Guid?>("ClearedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("cleared_by");

                    b.Property<string>("OurValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("our_value");

                    b.Property<Guid?>("OverrideActor")
                        .HasColumnType("uuid")
                        .HasColumnName("override_actor");

                    b.Property<DateTimeOffset>("OverrideAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("override_at");

                    b.Property<string>("PmsValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("pms_value");

                    b.Property<string>("PmsValueAtOverride")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("pms_value_at_override");

                    b.Property<DateTimeOffset>("RaisedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("raised_at");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<Guid>("StayId")
                        .HasColumnType("uuid")
                        .HasColumnName("stay_id");

                    b.HasKey("Id")
                        .HasName("pk_stay_disagreements");

                    b.HasIndex("StayId", "State")
                        .HasDatabaseName("ix_stay_disagreements_stay_id_state");

                    b.ToTable("stay_disagreements", "reservations");
                });

            modelBuilder.Entity("HotelOS.GuestOps.Domain.StayExternalRef", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_id");

                    b.Property<string>("IdentifierKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("identifier_kind");

                    b.Property<string>("IntegrationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("integration_id");

                    b.Property<Guid>("StayId")
                        .HasColumnType("uuid")
                        .HasColumnName("stay_id");

                    b.HasKey("Id")
                        .HasName("pk_stay_external_refs");

                    b.HasIndex("StayId")
                        .HasDatabaseName("ix_stay_external_refs_stay_id");

                    b.HasIndex("IntegrationId", "IdentifierKind", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("uq_stay_external_refs__identity");

                    b.ToTable("stay_external_refs", "reservations");
                });

            modelBuilder.Entity("HotelOS.GuestOps.Domain.StayGuest", b =>
                {
                    b.Property<Guid>("StayId")
                        .HasColumnType("uuid")
                        .HasColumnName("stay_id");

                    b.Property<Guid>("GuestId")
                        .HasColumnType("uuid")
                        .HasColumnName("guest_id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<bool?>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<int>("Origin")
                        .HasColumnType("integer")
                        .HasColumnName("origin");

                    b.HasKey("StayId", "GuestId")
                        .HasName("pk_stay_guests");

                    b.HasIndex("GuestId")
                        .HasDatabaseName("ix_stay_guests_guest_id");

                    b.ToTable("stay_guests", "reservations");
                });

            modelBuilder.Entity("HotelOS.GuestOps.Domain.StayLinkCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<Guid?>("DecidedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by");

                    b.Property<Guid>("HeldFactId")
                        .HasColumnType("uuid")
                        .HasColumnName("held_fact_id");

                    b.Property<Guid>("LocalStayId")
                        .HasColumnType("uuid")
                        .HasColumnName("local_stay_id");

                    b.Property<DateTimeOffset>("RaisedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("raised_at");

                    b.Property<double>("RankScore")
                        .HasColumnType("double precision")
                        .HasColumnName("rank_score");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_stay_link_candidates");

                    b.HasIndex("LocalStayId", "State")
                        .HasDatabaseName("ix_stay_link_candidates_local_stay_id_state");

                    b.ToTable("stay_link_candidates", "reservations");
                });

            modelBuilder.Entity("HotelOS.GuestOps.Domain.StayNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<Guid?>("Author")
                        .HasColumnType("uuid")
                        .HasColumnName("author");

                    b.Property<Guid>("StayId")
                        .HasColumnType("uuid")
                        .HasColumnName("stay_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_stay_notes");

                    b.HasIndex("StayId")
                        .HasDatabaseName("ix_stay_notes_stay_id");

                    b.ToTable("stay_notes", "reservations");
                });

            modelBuilder.Entity("HotelOS.GuestOps.Domain.StayReporting", b =>
                {
                    b.Property<Guid>("StayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("stay_id");

                    b.Property<string>("Authority")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("authority");

                    b.Property<DateTimeOffset?>("FiledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("filed_at");

                    b.Property<Guid?>("FiledBy")
                        .HasColumnType("uuid")
                        .HasColumnName("filed_by");

                    b.Property<string>("Reference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reference");

                    b.Property<DateOnly?>("RequiredBy")
                        .HasColumnType("date")
                        .HasColumnName("required_by");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<Guid>("StayId1")
                        .HasColumnType("uuid")
                        .HasColumnName("stay_id1");

                    b.HasKey("StayId")
                        .HasName("pk_stay_reporting");

                    b.HasIndex("StayId1")
                        .HasDatabaseName("ix_stay_reporting_stay_id1");

                    b.HasIndex("State", "RequiredBy")
                        .HasDatabaseName("ix_stay_reporting_state_required_by");

                    b.ToTable("stay_reporting", "reservations");
                });

            modelBuilder.Entity("HotelOS.GuestOps.Domain.StayRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<bool>("HandedOff")
                        .HasColumnType("boolean")
                        .HasColumnName("handed_off");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<DateTimeOffset>("LoggedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("logged_at");

                    b.Property<Guid?>("LoggedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("logged_by");

                    b.Property<Guid>("StayId")
                        .HasColumnType("uuid")
                        .HasColumnName("stay_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_stay_requests");

                    b.HasIndex("CorrelationId")
                        .IsUnique()
                        .HasDatabaseName("uq_stay_requests__correlation")
                        .HasFilter("correlation_id IS NOT NULL");

                    b.HasIndex("StayId")
                        .HasDatabaseName("ix_stay_requests_stay_id");

                    b.ToTable("stay_requests", "reservations");
                });

            modelBuilder.Entity("HotelOS.GuestOps.Domain.StaySource", b =>
                {
                    b.Property<Guid>("StayId")
                        .HasColumnType("uuid")
                        .HasColumnName("stay_id");

                    b.Property<int>("Adults")
                        .HasColumnType("integer")
                        .HasColumnName("adults");

                    b.Property<string>("Channel")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("channel");

                    b.Property<int>("Children")
                        .HasColumnType("integer")
                        .HasColumnName("children");

                    b.Property<string>("MarketCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("market_code");

                    b.Property<string>("MealPlan")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("meal_plan");

                    b.Property<string>("TravelAgent")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("travel_agent");

                    b.HasKey("StayId")
                        .HasName("pk_stay_sources");

                    b.HasIndex("Channel")
                        .HasDatabaseName("ix_stay_sources_channel");

                    b.ToTable("stay_sources", "reservations");
                });

            modelBuilder.Entity("HotelOS.GuestOps.Domain.StaySourceDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("IntegrationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("integration_id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<Guid>("StayId")
                        .HasColumnType("uuid")
                        .HasColumnName("stay_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_stay_source_detail");

                    b.HasIndex("StayId")
                        .HasDatabaseName("ix_stay_source_detail_stay_id");

                    b.ToTable("stay_source_detail", "reservations");
                });

            modelBuilder.Entity("HotelOS.GuestOps.Domain.StopSell", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("FromDate")
                        .HasColumnType("date")
                        .HasColumnName("from_date");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_type_id");

                    b.Property<DateTimeOffset>("SetAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("set_at");

                    b.Property<Guid?>("SetBy")
                        .HasColumnType("uuid")
                        .HasColumnName("set_by");

                    b.Property<DateOnly>("ToDate")
                        .HasColumnType("date")
                        .HasColumnName("to_date");

                    b.HasKey("Id")
                        .HasName("pk_stop_sells");

                    b.HasIndex("PropertyId", "RoomTypeId", "FromDate", "ToDate")
                        .HasDatabaseName("ix_stop_sells_property_id_room_type_id_from_date_to_date");

                    b.ToTable("stop_sells", "reservations", t =>
                        {
                            t.HasCheckConstraint("ck_stop_sells__range", "to_date >= from_date");
                        });
                });

            modelBuilder.Entity("HotelOS.GuestOps.Infrastructure.ReadModels.MasterDataRoom", b =>
                {
                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_type_id");

                    b.ToTable("rooms", "masterdata", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("HotelOS.Platform.PublishQueueEntry", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("EventId")
                        .HasName("pk_publish_state");

                    b.ToTable("publish_state", "event_store", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("HotelOS.Platform.StoredEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<int>("ActorType")
                        .HasColumnType("integer")
                        .HasColumnName("actor_type");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("aggregate_type");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("EntityVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_version");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<JsonDocument>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("session_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trace_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("EventId")
                        .HasName("pk_events");

                    b.ToTable("events", "event_store", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("HotelOS.GuestOps.Domain.Assignment", b =>
                {
                    b.HasOne("HotelOS.GuestOps.Domain.RoomStay", "Stay")
                        .WithMany("Assignments")
                        .HasForeignKey("StayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignments_stays_stay_id");

                    b.Navigation("Stay");
                });

            modelBuilder.Entity("HotelOS.GuestOps.Domain.BookingExternalRef", b =>
                {
                    b.HasOne("HotelOS.GuestOps.Domain.Booking", "Booking")
                        .WithMany("ExternalRefs")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_booking_external_refs_bookings_booking_id");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("HotelOS.GuestOps.Domain.CommercialTerms", b =>
                {
                    b.HasOne("HotelOS.GuestOps.Domain.RoomStay", "Stay")
                        .WithOne("Terms")
                        .HasForeignKey("HotelOS.GuestOps.Domain.CommercialTerms", "StayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_commercial_terms_stays_stay_id");

                    b.OwnsOne("HotelOS.GuestOps.Domain.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("CommercialTermsStayId")
                                .HasColumnType("uuid")
                                .HasColumnName("stay_id");

                            b1.Property<int>("Basis")
                                .HasColumnType("integer")
                                .HasColumnName("amount_tax_basis");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("amount_currency");

                            b1.Property<long>("MinorUnits")
                                .HasColumnType("bigint")
                                .HasColumnName("amount_minor_units");

                            b1.HasKey("CommercialTermsStayId");

                            b1.ToTable("commercial_terms", "reservations");

                            b1.WithOwner()
                                .HasForeignKey("CommercialTermsStayId")
                                .HasConstraintName("fk_commercial_terms_commercial_terms_stay_id");
                        });

                    b.OwnsOne("HotelOS.GuestOps.Domain.Money", "PenaltyAmount", b1 =>
                        {
                            b1.Property<Guid>("CommercialTermsStayId")
                                .HasColumnType("uuid")
                                .HasColumnName("stay_id");

                            b1.Property<int>("Basis")
                                .HasColumnType("integer")
                                .HasColumnName("penalty_tax_basis");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("penalty_currency");

                            b1.Property<long>("MinorUnits")
                                .HasColumnType("bigint")
                                .HasColumnName("penalty_minor_units");

                            b1.HasKey("CommercialTermsStayId");

                            b1.ToTable("commercial_terms", "reservations");

                            b1.WithOwner()
                                .HasForeignKey("CommercialTermsStayId")
                                .HasConstraintName("fk_commercial_terms_commercial_terms_stay_id");
                        });

                    b.Navigation("Amount");

                    b.Navigation("PenaltyAmount");

                    b.Navigation("Stay");
                });

            modelBuilder.Entity("HotelOS.GuestOps.Domain.ContactPoint", b =>
                {
                    b.HasOne("HotelOS.GuestOps.Domain.GuestIdentity", "Guest")
                        .WithMany("Contacts")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contact_points_guests_guest_id");

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("HotelOS.GuestOps.Domain.Registration", b =>
                {
                    b.HasOne("HotelOS.GuestOps.Domain.RoomStay", "Stay")
                        .WithMany()
                        .HasForeignKey("StayId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_registrations_stays_stay_id1");

                    b.Navigation("Stay");
                });

            modelBuilder.Entity("HotelOS.GuestOps.Domain.RoomStay", b =>
                {
                    b.HasOne("HotelOS.GuestOps.Domain.Booking", "Booking")
                        .WithMany("Stays")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_room_stays_bookings_booking_id");

                    b.OwnsOne("HotelOS.GuestOps.Domain.StayTime", "ArrivalAt", b1 =>
                        {
                            b1.Property<Guid>("RoomStayId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset?>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("arrival_at");

                            b1.Property<int>("Basis")
                                .HasColumnType("integer")
                                .HasColumnName("arrival_basis");

                            b1.HasKey("RoomStayId");

                            b1.ToTable("room_stays", "reservations");

                            b1.WithOwner()
                                .HasForeignKey("RoomStayId")
                                .HasConstraintName("fk_room_stays_room_stays_id");
                        });

                    b.OwnsOne("HotelOS.GuestOps.Domain.StayTime", "DepartureAt", b1 =>
                        {
                            b1.Property<Guid>("RoomStayId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset?>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("departure_at");

                            b1.Property<int>("Basis")
                                .HasColumnType("integer")
                                .HasColumnName("departure_basis");

                            b1.HasKey("RoomStayId");

                            b1.ToTable("room_stays", "reservations");

                            b1.WithOwner()
                                .HasForeignKey("RoomStayId")
                                .HasConstraintName("fk_room_stays_room_stays_id");
                        });

                    b.Navigation("ArrivalAt")
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("DepartureAt")
                        .IsRequired();
                });

            modelBuilder.Entity("HotelOS.GuestOps.Domain.StayAbsence", b =>
                {
                    b.HasOne("HotelOS.GuestOps.Domain.RoomStay", "Stay")
                        .WithMany("Absences")
                        .HasForeignKey("StayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stay_absences_room_stays_stay_id");

                    b.Navigation("Stay");
                });

            modelBuilder.Entity("HotelOS.GuestOps.Domain.StayDisagreement", b =>
                {
                    b.HasOne("HotelOS.GuestOps.Domain.RoomStay", "Stay")
                        .WithMany()
                        .HasForeignKey("StayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stay_disagreements_room_stays_stay_id");

                    b.Navigation("Stay");
                });

            modelBuilder.Entity("HotelOS.GuestOps.Domain.StayExternalRef", b =>
                {
                    b.HasOne("HotelOS.GuestOps.Domain.RoomStay", "Stay")
                        .WithMany("ExternalRefs")
                        .HasForeignKey("StayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stay_external_refs_stays_stay_id");

                    b.Navigation("Stay");
                });

            modelBuilder.Entity("HotelOS.GuestOps.Domain.StayGuest", b =>
                {
                    b.HasOne("HotelOS.GuestOps.Domain.GuestIdentity", "Guest")
                        .WithMany()
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stay_guests_guests_guest_id");

                    b.HasOne("HotelOS.GuestOps.Domain.RoomStay", "Stay")
                        .WithMany("Party")
                        .HasForeignKey("StayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stay_guests_room_stays_stay_id");

                    b.Navigation("Guest");

                    b.Navigation("Stay");
                });

            modelBuilder.Entity("HotelOS.GuestOps.Domain.StayLinkCandidate", b =>
                {
                    b.HasOne("HotelOS.GuestOps.Domain.RoomStay", "LocalStay")
                        .WithMany()
                        .HasForeignKey("LocalStayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stay_link_candidates_room_stays_local_stay_id");

                    b.Navigation("LocalStay");
                });

            modelBuilder.Entity("HotelOS.GuestOps.Domain.StayNote", b =>
                {
                    b.HasOne("HotelOS.GuestOps.Domain.RoomStay", "Stay")
                        .WithMany()
                        .HasForeignKey("StayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stay_notes_room_stays_stay_id");

                    b.Navigation("Stay");
                });

            modelBuilder.Entity("HotelOS.GuestOps.Domain.StayReporting", b =>
                {
                    b.HasOne("HotelOS.GuestOps.Domain.RoomStay", "Stay")
                        .WithMany()
                        .HasForeignKey("StayId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stay_reporting_room_stays_stay_id1");

                    b.Navigation("Stay");
                });

            modelBuilder.Entity("HotelOS.GuestOps.Domain.StayRequest", b =>
                {
                    b.HasOne("HotelOS.GuestOps.Domain.RoomStay", "Stay")
                        .WithMany()
                        .HasForeignKey("StayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stay_requests_room_stays_stay_id");

                    b.Navigation("Stay");
                });

            modelBuilder.Entity("HotelOS.GuestOps.Domain.StaySource", b =>
                {
                    b.HasOne("HotelOS.GuestOps.Domain.RoomStay", "Stay")
                        .WithOne("Source")
                        .HasForeignKey("HotelOS.GuestOps.Domain.StaySource", "StayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stay_sources_room_stays_stay_id");

                    b.Navigation("Stay");
                });

            modelBuilder.Entity("HotelOS.GuestOps.Domain.StaySourceDetail", b =>
                {
                    b.HasOne("HotelOS.GuestOps.Domain.StaySource", "Source")
                        .WithMany("Detail")
                        .HasForeignKey("StayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stay_source_detail_stay_sources_stay_id");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("HotelOS.GuestOps.Domain.Booking", b =>
                {
                    b.Navigation("ExternalRefs");

                    b.Navigation("Stays");
                });

            modelBuilder.Entity("HotelOS.GuestOps.Domain.GuestIdentity", b =>
                {
                    b.Navigation("Contacts");
                });

            modelBuilder.Entity("HotelOS.GuestOps.Domain.RoomStay", b =>
                {
                    b.Navigation("Absences");

                    b.Navigation("Assignments");

                    b.Navigation("ExternalRefs");

                    b.Navigation("Party");

                    b.Navigation("Source");

                    b.Navigation("Terms");
                });

            modelBuilder.Entity("HotelOS.GuestOps.Domain.StaySource", b =>
                {
                    b.Navigation("Detail");
                });
#pragma warning restore 612, 618
        }
    }
}
