// <auto-generated />
using System;
using System.Text.Json;
using HotelOS.Jobs.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HotelOS.Jobs.Infrastructure.Migrations
{
    [DbContext(typeof(JobsDbContext))]
    [Migration("20260904044734_InitialJobs")]
    partial class InitialJobs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("jobs")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HotelOS.Jobs.Domain.Catalogue.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("department_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_category");

                    b.HasIndex("OrganizationId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_category_organization_id_code");

                    b.ToTable("category", "jobs", t =>
                        {
                            t.HasCheckConstraint("ck_category__department_code_present", "length(btrim(department_code)) > 0");
                        });
                });

            modelBuilder.Entity("HotelOS.Jobs.Domain.Catalogue.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultPriority")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("default_priority");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<int?>("DueWithinMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("due_within_minutes");

                    b.Property<bool>("GuestRequestable")
                        .HasColumnType("boolean")
                        .HasColumnName("guest_requestable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PhotoOnCompletion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("photo_on_completion");

                    b.Property<bool>("RestrictedByDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("restricted_by_default");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_item");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_item_category_id");

                    b.HasIndex("OrganizationId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_item_organization_id_code");

                    b.ToTable("item", "jobs", t =>
                        {
                            t.HasCheckConstraint("ck_item__default_priority", "default_priority IN ('P1', 'P2', 'P3')");

                            t.HasCheckConstraint("ck_item__due_positive", "due_within_minutes IS NULL OR due_within_minutes > 0");

                            t.HasCheckConstraint("ck_item__photo", "photo_on_completion IN ('NONE', 'OPTIONAL', 'REQUIRED')");
                        });
                });

            modelBuilder.Entity("HotelOS.Jobs.Domain.Catalogue.ItemAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("alias");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("Language")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("language");

                    b.HasKey("Id")
                        .HasName("pk_item_alias");

                    b.HasIndex("Alias")
                        .HasDatabaseName("ix_item_alias_alias");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_item_alias_item_id");

                    b.ToTable("item_alias", "jobs");
                });

            modelBuilder.Entity("HotelOS.Jobs.Domain.Catalogue.Resolution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<bool>("NoteRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("note_required");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("Id")
                        .HasName("pk_resolution");

                    b.HasIndex("OrganizationId", "CategoryId", "ItemId")
                        .HasDatabaseName("ix_resolution_organization_id_category_id_item_id");

                    b.ToTable("resolution", "jobs", t =>
                        {
                            t.HasCheckConstraint("ck_resolution__item_needs_category", "item_id IS NULL OR category_id IS NOT NULL");
                        });
                });

            modelBuilder.Entity("HotelOS.Jobs.Domain.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<Guid?>("ConcernPolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("concern_policy_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Cycle")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("cycle");

                    b.Property<string>("DeleteReason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("delete_reason");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("department_code");

                    b.Property<string>("Details")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("details");

                    b.Property<DateTimeOffset?>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<string>("HoldReason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("hold_reason");

                    b.Property<DateTimeOffset?>("HoldUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hold_until");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("JobNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("job_number");

                    b.Property<string>("JobStatus")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("job_status");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<Guid?>("ParentJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_job_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("priority");

                    b.Property<string>("PriorityDecidedBy")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("priority_decided_by");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<Guid?>("RaisedById")
                        .HasColumnType("uuid")
                        .HasColumnName("raised_by_id");

                    b.Property<string>("RaisedKind")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("raised_kind");

                    b.Property<string>("RaisedVia")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("raised_via");

                    b.Property<bool>("Restricted")
                        .HasColumnType("boolean")
                        .HasColumnName("restricted");

                    b.Property<DateOnly?>("ScheduledFor")
                        .HasColumnType("date")
                        .HasColumnName("scheduled_for");

                    b.Property<Guid?>("StayId")
                        .HasColumnType("uuid")
                        .HasColumnName("stay_id");

                    b.Property<int?>("StepNo")
                        .HasColumnType("integer")
                        .HasColumnName("step_no");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("summary");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_job");

                    b.HasIndex("ParentJobId")
                        .HasDatabaseName("ix_job_parent_job_id");

                    b.HasIndex("StayId")
                        .HasDatabaseName("ix_job_stay_id");

                    b.HasIndex("PropertyId", "JobNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_job_property_id_job_number");

                    b.HasIndex("PropertyId", "ScheduledFor")
                        .HasDatabaseName("ix_job_property_id_scheduled_for");

                    b.HasIndex("PropertyId", "JobStatus", "DepartmentCode")
                        .HasDatabaseName("ix_job_property_id_job_status_department_code");

                    b.ToTable("job", "jobs", t =>
                        {
                            t.HasCheckConstraint("ck_job__deleted_has_reason", "deleted_at IS NULL OR delete_reason IS NOT NULL");

                            t.HasCheckConstraint("ck_job__guest_has_stay", "raised_kind <> 'GUEST' OR stay_id IS NOT NULL");

                            t.HasCheckConstraint("ck_job__hold_pair", "job_status <> 'ON_HOLD' OR hold_reason IS NOT NULL");

                            t.HasCheckConstraint("ck_job__priority", "priority IN ('P1', 'P2', 'P3', 'NOT_TRIAGED')");

                            t.HasCheckConstraint("ck_job__priority_decided_by", "priority_decided_by IN ('MANUAL', 'FLOW', 'CATALOGUE', 'NONE')");

                            t.HasCheckConstraint("ck_job__raised_kind", "raised_kind IN ('STAFF', 'GUEST', 'APPLICATION')");

                            t.HasCheckConstraint("ck_job__raised_via", "raised_via IN ('APP', 'QR', 'GUEST_APP', 'WHATSAPP')");

                            t.HasCheckConstraint("ck_job__status", "job_status IN ('SCHEDULED', 'RAISED', 'ASSIGNED', 'ACCEPTED', 'IN_PROGRESS', 'ON_HOLD', 'RESOLVED', 'CLOSED', 'CANCELLED')");

                            t.HasCheckConstraint("ck_job__step_pair", "(parent_job_id IS NULL) = (step_no IS NULL)");
                        });
                });

            modelBuilder.Entity("HotelOS.Jobs.Domain.JobAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid?>("AssignedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by");

                    b.Property<Guid?>("AssigneeUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_user_id");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<string>("How")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("how");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id")
                        .HasName("pk_job_assignment");

                    b.HasIndex("JobId", "EndedAt")
                        .HasDatabaseName("ix_job_assignment_job_id_ended_at");

                    b.HasIndex("PropertyId", "AssigneeUserId", "EndedAt")
                        .HasDatabaseName("ix_job_assignment_property_id_assignee_user_id_ended_at");

                    b.ToTable("job_assignment", "jobs", t =>
                        {
                            t.HasCheckConstraint("ck_job_assignment__how", "how IN ('MANUAL', 'AUTO')");

                            t.HasCheckConstraint("ck_job_assignment__one_target", "(assignee_user_id IS NOT NULL)::int + (team_id IS NOT NULL)::int <= 1");
                        });
                });

            modelBuilder.Entity("HotelOS.Jobs.Domain.JobAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AddedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("added_by");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<long>("Bytes")
                        .HasColumnType("bigint")
                        .HasColumnName("bytes");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.HasKey("Id")
                        .HasName("pk_job_attachment");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_job_attachment_job_id");

                    b.ToTable("job_attachment", "jobs");
                });

            modelBuilder.Entity("HotelOS.Jobs.Domain.JobConcernHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountableRole")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("accountable_role");

                    b.Property<Guid?>("AccountableUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountable_user_id");

                    b.Property<string>("Concern")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("concern");

                    b.Property<Guid?>("ConcernPolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("concern_policy_id");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<int>("LadderStep")
                        .HasColumnType("integer")
                        .HasColumnName("ladder_step");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("Since")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("since");

                    b.HasKey("Id")
                        .HasName("pk_job_concern_history");

                    b.HasIndex("JobId", "Since")
                        .HasDatabaseName("ix_job_concern_history_job_id_since");

                    b.HasIndex("PropertyId", "Concern", "Since")
                        .HasDatabaseName("ix_job_concern_history_property_id_concern_since");

                    b.ToTable("job_concern_history", "jobs", t =>
                        {
                            t.HasCheckConstraint("ck_job_concern__concern", "concern IN ('ON_TRACK', 'AT_RISK', 'BREACHED', 'STUCK')");

                            t.HasCheckConstraint("ck_job_concern__role", "accountable_role IN ('ASSIGNEE', 'SUPERVISOR', 'MANAGER', 'JOBS_MANAGER', 'GENERAL_MANAGER')");
                        });
                });

            modelBuilder.Entity("HotelOS.Jobs.Domain.JobLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid?>("LinkedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_by");

                    b.Property<Guid>("LinkedJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_job_id");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.HasKey("Id")
                        .HasName("pk_job_link");

                    b.HasIndex("JobId", "LinkedJobId")
                        .IsUnique()
                        .HasDatabaseName("ix_job_link_job_id_linked_job_id");

                    b.ToTable("job_link", "jobs", t =>
                        {
                            t.HasCheckConstraint("ck_job_link__not_self", "job_id <> linked_job_id");
                        });
                });

            modelBuilder.Entity("HotelOS.Jobs.Domain.JobNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("AuthorKind")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("author_kind");

                    b.Property<bool>("Internal")
                        .HasColumnType("boolean")
                        .HasColumnName("internal");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_job_note");

                    b.HasIndex("JobId", "At")
                        .HasDatabaseName("ix_job_note_job_id_at");

                    b.ToTable("job_note", "jobs", t =>
                        {
                            t.HasCheckConstraint("ck_job_note__author_kind", "author_kind IN ('STAFF', 'GUEST', 'APPLICATION')");
                        });
                });

            modelBuilder.Entity("HotelOS.Jobs.Domain.JobNudge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AsRole")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("as_role");

                    b.Property<string>("Concern")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("concern");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<Guid>("ToUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_user_id");

                    b.HasKey("Id")
                        .HasName("pk_job_nudge");

                    b.HasIndex("JobId", "SentAt")
                        .HasDatabaseName("ix_job_nudge_job_id_sent_at");

                    b.HasIndex("PropertyId", "ToUserId", "ReadAt")
                        .HasDatabaseName("ix_job_nudge_property_id_to_user_id_read_at");

                    b.ToTable("job_nudge", "jobs");
                });

            modelBuilder.Entity("HotelOS.Jobs.Domain.JobRating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<DateTimeOffset>("RatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rated_at");

                    b.Property<int>("Stars")
                        .HasColumnType("integer")
                        .HasColumnName("stars");

                    b.Property<Guid>("StayId")
                        .HasColumnType("uuid")
                        .HasColumnName("stay_id");

                    b.Property<string>("Text")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_job_rating");

                    b.HasIndex("JobId")
                        .IsUnique()
                        .HasDatabaseName("ix_job_rating_job_id");

                    b.ToTable("job_rating", "jobs", t =>
                        {
                            t.HasCheckConstraint("ck_job_rating__stars", "stars BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("HotelOS.Jobs.Domain.JobReminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("FiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fired_at");

                    b.Property<Guid>("ForUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("for_user_id");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("kind");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("note");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<DateTimeOffset>("RemindAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("remind_at");

                    b.HasKey("Id")
                        .HasName("pk_job_reminder");

                    b.HasIndex("PropertyId", "FiredAt", "RemindAt")
                        .HasDatabaseName("ix_job_reminder_property_id_fired_at_remind_at");

                    b.ToTable("job_reminder", "jobs", t =>
                        {
                            t.HasCheckConstraint("ck_job_reminder__kind", "kind IN ('MANUAL', 'HOLD')");
                        });
                });

            modelBuilder.Entity("HotelOS.Jobs.Domain.JobResolution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("note");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<Guid?>("ResolutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolution_id");

                    b.Property<DateTimeOffset>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid>("ResolvedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by");

                    b.HasKey("Id")
                        .HasName("pk_job_resolution");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_job_resolution_job_id");

                    b.ToTable("job_resolution", "jobs", t =>
                        {
                            t.HasCheckConstraint("ck_job_resolution__other_needs_note", "resolution_id IS NOT NULL OR note IS NOT NULL");
                        });
                });

            modelBuilder.Entity("HotelOS.Jobs.Domain.JobStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<Guid?>("ByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("by_user_id");

                    b.Property<string>("ByWhat")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("by_what");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("from_status");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("note");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("to_status");

                    b.HasKey("Id")
                        .HasName("pk_job_status_history");

                    b.HasIndex("JobId", "At")
                        .HasDatabaseName("ix_job_status_history_job_id_at");

                    b.ToTable("job_status_history", "jobs");
                });

            modelBuilder.Entity("HotelOS.Jobs.Domain.JobWorkSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("PauseReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("pause_reason");

                    b.Property<DateTimeOffset?>("PausedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paused_at");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<DateTimeOffset?>("ResumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resumed_at");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<DateTimeOffset?>("StoppedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stopped_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("WorkedSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("worked_seconds");

                    b.HasKey("Id")
                        .HasName("pk_job_work_session");

                    b.HasIndex("JobId", "StoppedAt")
                        .HasDatabaseName("ix_job_work_session_job_id_stopped_at");

                    b.HasIndex("PropertyId", "UserId", "StoppedAt")
                        .HasDatabaseName("ix_job_work_session_property_id_user_id_stopped_at");

                    b.ToTable("job_work_session", "jobs");
                });

            modelBuilder.Entity("HotelOS.Jobs.Domain.Policy.ClosingPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AutoCloseHours")
                        .HasColumnType("integer")
                        .HasColumnName("auto_close_hours");

                    b.Property<string>("DepartmentCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("department_code");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<bool>("RatingOnClose")
                        .HasColumnType("boolean")
                        .HasColumnName("rating_on_close");

                    b.HasKey("Id")
                        .HasName("pk_closing_policy");

                    b.HasIndex("PropertyId", "DepartmentCode")
                        .IsUnique()
                        .HasDatabaseName("ix_closing_policy_property_id_department_code");

                    b.ToTable("closing_policy", "jobs", t =>
                        {
                            t.HasCheckConstraint("ck_closing__hours", "auto_close_hours >= 0");
                        });
                });

            modelBuilder.Entity("HotelOS.Jobs.Domain.Policy.ConcernLadderStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DelayMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("delay_minutes");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("priority");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<int>("StepNo")
                        .HasColumnType("integer")
                        .HasColumnName("step_no");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("trigger");

                    b.HasKey("Id")
                        .HasName("pk_concern_ladder_step");

                    b.HasIndex("PolicyId", "Priority", "StepNo")
                        .IsUnique()
                        .HasDatabaseName("ix_concern_ladder_step_policy_id_priority_step_no");

                    b.ToTable("concern_ladder_step", "jobs", t =>
                        {
                            t.HasCheckConstraint("ck_ladder__delay", "delay_minutes >= 0");

                            t.HasCheckConstraint("ck_ladder__role", "role IN ('ASSIGNEE', 'SUPERVISOR', 'MANAGER', 'JOBS_MANAGER', 'GENERAL_MANAGER')");

                            t.HasCheckConstraint("ck_ladder__trigger", "trigger IN ('AT_RISK', 'BREACHED')");
                        });
                });

            modelBuilder.Entity("HotelOS.Jobs.Domain.Policy.ConcernPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DepartmentCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("department_code");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<int>("UntriagedStuckMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("untriaged_stuck_minutes");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_concern_policy");

                    b.HasIndex("PropertyId", "DepartmentCode", "CategoryId", "ItemId")
                        .HasDatabaseName("ix_concern_policy_property_id_department_code_category_id_item");

                    b.ToTable("concern_policy", "jobs", t =>
                        {
                            t.HasCheckConstraint("ck_concern_policy__scope_nested", "(category_id IS NULL OR department_code IS NOT NULL) AND (item_id IS NULL OR category_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("HotelOS.Jobs.Domain.Policy.ConcernPolicyRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AtRiskPercent")
                        .HasColumnType("integer")
                        .HasColumnName("at_risk_percent");

                    b.Property<int?>("DueWithinMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("due_within_minutes");

                    b.Property<bool>("ManagerAtRisk")
                        .HasColumnType("boolean")
                        .HasColumnName("manager_at_risk");

                    b.Property<int?>("NoSessionMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("no_session_minutes");

                    b.Property<int?>("NotAcceptedMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("not_accepted_minutes");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("priority");

                    b.Property<bool>("RunsOutsidePresence")
                        .HasColumnType("boolean")
                        .HasColumnName("runs_outside_presence");

                    b.HasKey("Id")
                        .HasName("pk_concern_policy_rule");

                    b.HasIndex("PolicyId", "Priority")
                        .IsUnique()
                        .HasDatabaseName("ix_concern_policy_rule_policy_id_priority");

                    b.ToTable("concern_policy_rule", "jobs", t =>
                        {
                            t.HasCheckConstraint("ck_concern_rule__at_risk", "at_risk_percent BETWEEN 1 AND 99");

                            t.HasCheckConstraint("ck_concern_rule__priority", "priority IN ('P1', 'P2', 'P3')");
                        });
                });

            modelBuilder.Entity("HotelOS.Jobs.Domain.Policy.ConcernSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Concern")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("concern");

                    b.Property<string>("DepartmentCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("department_code");

                    b.Property<string>("OnlyPriority")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("only_priority");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<int?>("RepeatMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("repeat_minutes");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_concern_subscription");

                    b.HasIndex("PropertyId", "Role")
                        .HasDatabaseName("ix_concern_subscription_property_id_role");

                    b.ToTable("concern_subscription", "jobs", t =>
                        {
                            t.HasCheckConstraint("ck_subscription__role", "role IN ('ASSIGNEE', 'SUPERVISOR', 'MANAGER', 'JOBS_MANAGER', 'GENERAL_MANAGER')");
                        });
                });

            modelBuilder.Entity("HotelOS.Jobs.Domain.Policy.DepartmentPresence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("department_code");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<bool>("FollowShifts")
                        .HasColumnType("boolean")
                        .HasColumnName("follow_shifts");

                    b.Property<int>("OnShift")
                        .HasColumnType("integer")
                        .HasColumnName("on_shift");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<DateTimeOffset?>("Since")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("since");

                    b.Property<bool>("Staffed")
                        .HasColumnType("boolean")
                        .HasColumnName("staffed");

                    b.HasKey("Id")
                        .HasName("pk_department_presence");

                    b.HasIndex("PropertyId", "DepartmentCode")
                        .IsUnique()
                        .HasDatabaseName("ix_department_presence_property_id_department_code");

                    b.ToTable("department_presence", "jobs");
                });

            modelBuilder.Entity("HotelOS.Jobs.Domain.Policy.HoldPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("MaxHoldDays")
                        .HasColumnType("integer")
                        .HasColumnName("max_hold_days");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<bool>("WarnAssigneeOnDay")
                        .HasColumnType("boolean")
                        .HasColumnName("warn_assignee_on_day");

                    b.Property<int>("WarnDaysBefore")
                        .HasColumnType("integer")
                        .HasColumnName("warn_days_before");

                    b.Property<string>("WarnRole")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("warn_role");

                    b.HasKey("Id")
                        .HasName("pk_hold_policy");

                    b.HasIndex("PropertyId")
                        .IsUnique()
                        .HasDatabaseName("ix_hold_policy_property_id");

                    b.ToTable("hold_policy", "jobs", t =>
                        {
                            t.HasCheckConstraint("ck_hold__warn_role", "warn_role IN ('ASSIGNEE', 'SUPERVISOR', 'MANAGER', 'JOBS_MANAGER', 'GENERAL_MANAGER')");
                        });
                });

            modelBuilder.Entity("HotelOS.Jobs.Domain.Policy.PropertyItemPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("ActiveHere")
                        .HasColumnType("boolean")
                        .HasColumnName("active_here");

                    b.Property<string>("AutoAssign")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("auto_assign");

                    b.Property<Guid?>("AutoAssignTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("auto_assign_team_id");

                    b.Property<Guid?>("ConcernPolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("concern_policy_id");

                    b.Property<string>("DefaultPriority")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("default_priority");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<int?>("DueWithinMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("due_within_minutes");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_property_item_policy");

                    b.HasIndex("PropertyId", "ItemId")
                        .IsUnique()
                        .HasDatabaseName("ix_property_item_policy_property_id_item_id");

                    b.ToTable("property_item_policy", "jobs", t =>
                        {
                            t.HasCheckConstraint("ck_item_policy__auto_assign", "auto_assign IN ('USER', 'TEAM')");

                            t.HasCheckConstraint("ck_item_policy__priority", "default_priority IS NULL OR default_priority IN ('P1', 'P2', 'P3')");
                        });
                });

            modelBuilder.Entity("HotelOS.Jobs.Domain.Policy.ServiceHours", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DepartmentCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("department_code");

                    b.Property<TimeOnly>("From")
                        .HasColumnType("time without time zone")
                        .HasColumnName("from");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<TimeOnly>("To")
                        .HasColumnType("time without time zone")
                        .HasColumnName("to");

                    b.HasKey("Id")
                        .HasName("pk_service_hours");

                    b.HasIndex("PropertyId", "DepartmentCode")
                        .IsUnique()
                        .HasDatabaseName("ix_service_hours_property_id_department_code");

                    b.ToTable("service_hours", "jobs");
                });

            modelBuilder.Entity("HotelOS.Jobs.Domain.PropertyJobSequence", b =>
                {
                    b.Property<Guid>("PropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<long>("Next")
                        .HasColumnType("bigint")
                        .HasColumnName("next");

                    b.Property<string>("PropertyCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("property_code");

                    b.HasKey("PropertyId")
                        .HasName("pk_property_job_sequence");

                    b.ToTable("property_job_sequence", "jobs");
                });

            modelBuilder.Entity("HotelOS.Platform.PublishQueueEntry", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("EventId")
                        .HasName("pk_publish_state");

                    b.ToTable("publish_state", "event_store", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("HotelOS.Platform.StoredEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<int>("ActorType")
                        .HasColumnType("integer")
                        .HasColumnName("actor_type");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("aggregate_type");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("EntityVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_version");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<JsonDocument>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("session_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trace_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("EventId")
                        .HasName("pk_events");

                    b.ToTable("events", "event_store", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("HotelOS.Jobs.Domain.Catalogue.Item", b =>
                {
                    b.HasOne("HotelOS.Jobs.Domain.Catalogue.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_category_category_id");
                });

            modelBuilder.Entity("HotelOS.Jobs.Domain.Catalogue.ItemAlias", b =>
                {
                    b.HasOne("HotelOS.Jobs.Domain.Catalogue.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_alias_item_item_id");
                });

            modelBuilder.Entity("HotelOS.Jobs.Domain.Policy.ConcernLadderStep", b =>
                {
                    b.HasOne("HotelOS.Jobs.Domain.Policy.ConcernPolicy", null)
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_concern_ladder_step_concern_policy_policy_id");
                });

            modelBuilder.Entity("HotelOS.Jobs.Domain.Policy.ConcernPolicyRule", b =>
                {
                    b.HasOne("HotelOS.Jobs.Domain.Policy.ConcernPolicy", null)
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_concern_policy_rule_concern_policy_policy_id");
                });
#pragma warning restore 612, 618
        }
    }
}
