// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using HotelOS.RoomCare.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HotelOS.RoomCare.Infrastructure.Migrations
{
    [DbContext(typeof(RoomCareDbContext))]
    [Migration("20260919102235_MasterDataStaffDisplayNameNullable")]
    partial class MasterDataStaffDisplayNameNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("roomcare")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HotelOS.Platform.PublishQueueEntry", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("EventId")
                        .HasName("pk_publish_state");

                    b.ToTable("publish_state", "event_store", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("HotelOS.Platform.StoredEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<int>("ActorType")
                        .HasColumnType("integer")
                        .HasColumnName("actor_type");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("aggregate_type");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("EntityVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_version");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<JsonDocument>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("session_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trace_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("EventId")
                        .HasName("pk_events");

                    b.ToTable("events", "event_store", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("HotelOS.RoomCare.Domain.AreaSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<int>("Minutes")
                        .HasColumnType("integer")
                        .HasColumnName("minutes");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.PrimitiveCollection<List<TimeOnly>>("Times")
                        .IsRequired()
                        .HasColumnType("time without time zone[]")
                        .HasColumnName("times");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_area_schedule");

                    b.HasIndex("PropertyId", "LocationId")
                        .IsUnique()
                        .HasDatabaseName("ix_area_schedule_property_id_location_id");

                    b.ToTable("area_schedule", "roomcare", t =>
                        {
                            t.HasCheckConstraint("ck_area_schedule__minutes", "minutes > 0");
                        });
                });

            modelBuilder.Entity("HotelOS.RoomCare.Domain.DeepClean", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("BlockAppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("block_applied_at");

                    b.Property<string>("BlockCorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("block_correlation_id");

                    b.Property<DateTimeOffset?>("BlockRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("block_requested_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DoneOn")
                        .HasColumnType("date")
                        .HasColumnName("done_on");

                    b.Property<DateOnly>("DueOn")
                        .HasColumnType("date")
                        .HasColumnName("due_on");

                    b.Property<string>("JobCorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("job_correlation_id");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("JobStatusSeen")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("job_status_seen");

                    b.Property<Guid?>("PlannedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("planned_by");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<DateOnly?>("WindowFrom")
                        .HasColumnType("date")
                        .HasColumnName("window_from");

                    b.Property<DateOnly?>("WindowTo")
                        .HasColumnType("date")
                        .HasColumnName("window_to");

                    b.HasKey("Id")
                        .HasName("pk_deep_clean");

                    b.HasIndex("JobCorrelationId")
                        .HasDatabaseName("ix_deep_clean_job_correlation_id");

                    b.HasIndex("PropertyId", "RoomId", "DueOn")
                        .IsUnique()
                        .HasDatabaseName("ix_deep_clean_property_id_room_id_due_on");

                    b.ToTable("deep_clean", "roomcare", t =>
                        {
                            t.HasCheckConstraint("ck_deep_clean__status", "\"status\" IN ('PLANNED', 'BLOCK_REQUESTED', 'BLOCKED', 'IN_PROGRESS', 'RETURNING', 'DONE', 'CANCELLED')");

                            t.HasCheckConstraint("ck_deep_clean__window_order", "window_from IS NULL OR window_to IS NULL OR window_from <= window_to");
                        });
                });

            modelBuilder.Entity("HotelOS.RoomCare.Domain.DeepCleanPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("EveryMonths")
                        .HasColumnType("integer")
                        .HasColumnName("every_months");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_type_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_deep_clean_plan");

                    b.HasIndex("PropertyId", "RoomTypeId")
                        .IsUnique()
                        .HasDatabaseName("ix_deep_clean_plan_property_id_room_type_id");

                    b.ToTable("deep_clean_plan", "roomcare", t =>
                        {
                            t.HasCheckConstraint("ck_deep_clean_plan__months", "every_months > 0");
                        });
                });

            modelBuilder.Entity("HotelOS.RoomCare.Domain.PostingSeen", b =>
                {
                    b.Property<Guid>("PostingId")
                        .HasColumnType("uuid")
                        .HasColumnName("posting_id");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("department_code");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<DateTimeOffset>("PostedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("PostingId")
                        .HasName("pk_posting_seen");

                    b.HasIndex("PropertyId", "DepartmentCode", "EndedAt")
                        .HasDatabaseName("ix_posting_seen_property_id_department_code_ended_at");

                    b.ToTable("posting_seen", "roomcare");
                });

            modelBuilder.Entity("HotelOS.RoomCare.Domain.PrepareRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<Guid?>("ById")
                        .HasColumnType("uuid")
                        .HasColumnName("by_id");

                    b.Property<string>("ByKind")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("by_kind");

                    b.Property<int>("ChangesSincePrevious")
                        .HasColumnType("integer")
                        .HasColumnName("changes_since_previous");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("kind");

                    b.Property<DateOnly>("OperatingDay")
                        .HasColumnType("date")
                        .HasColumnName("operating_day");

                    b.Property<int>("Pending")
                        .HasColumnType("integer")
                        .HasColumnName("pending");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<int>("RoomsConsidered")
                        .HasColumnType("integer")
                        .HasColumnName("rooms_considered");

                    b.Property<int>("TasksCreated")
                        .HasColumnType("integer")
                        .HasColumnName("tasks_created");

                    b.Property<int>("TasksSkipped")
                        .HasColumnType("integer")
                        .HasColumnName("tasks_skipped");

                    b.Property<int>("TasksUpdated")
                        .HasColumnType("integer")
                        .HasColumnName("tasks_updated");

                    b.Property<int>("Unassignable")
                        .HasColumnType("integer")
                        .HasColumnName("unassignable");

                    b.Property<string>("Via")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("via");

                    b.Property<string>("Window")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("window");

                    b.HasKey("Id")
                        .HasName("pk_prepare_run");

                    b.HasIndex("PropertyId", "OperatingDay", "Window", "At")
                        .HasDatabaseName("ix_prepare_run_property_id_operating_day_window_at");

                    b.ToTable("prepare_run", "roomcare", t =>
                        {
                            t.HasCheckConstraint("ck_prepare_run__by_kind", "\"by_kind\" IN ('USER', 'SYSTEM', 'APPLICATION')");

                            t.HasCheckConstraint("ck_prepare_run__kind", "\"kind\" IN ('FIRST', 'RECONCILE')");

                            t.HasCheckConstraint("ck_prepare_run__via", "\"via\" IN ('APP', 'HOSPILOT')");

                            t.HasCheckConstraint("ck_prepare_run__window", "\"window\" IN ('MORNING', 'EVENING')");
                        });
                });

            modelBuilder.Entity("HotelOS.RoomCare.Domain.PropertyPolicy", b =>
                {
                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<string>("AssignmentStrategy")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("assignment_strategy");

                    b.Property<string>("BoardDefaultView")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("board_default_view");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("department_code");

                    b.Property<int>("DndRecheckMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("dnd_recheck_minutes");

                    b.Property<int>("LinenEveryDays")
                        .HasColumnType("integer")
                        .HasColumnName("linen_every_days");

                    b.Property<string>("LinenRuleKind")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("linen_rule_kind");

                    b.Property<string>("OnDepartureCondition")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("on_departure_condition");

                    b.PrimitiveCollection<List<string>>("PriorityLadder")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("priority_ladder");

                    b.Property<int>("RefreshAfterDays")
                        .HasColumnType("integer")
                        .HasColumnName("refresh_after_days");

                    b.Property<string>("StatesDefaultView")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("states_default_view");

                    b.Property<string>("StaySource")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("stay_source");

                    b.Property<int>("SupervisorAfterDays")
                        .HasColumnType("integer")
                        .HasColumnName("supervisor_after_days");

                    b.Property<string>("Towels")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("towels");

                    b.Property<string>("TriggerMode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("trigger_mode");

                    b.Property<bool>("TurndownEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("turndown_enabled");

                    b.Property<string>("UnsoldDeparture")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("unsold_departure");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<string>("WhoLeads")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("who_leads");

                    b.HasKey("PropertyId")
                        .HasName("pk_property_policy");

                    b.ToTable("property_policy", "roomcare", t =>
                        {
                            t.HasCheckConstraint("ck_property_policy__board_view", "\"board_default_view\" IN ('MAP', 'WALL')");

                            t.HasCheckConstraint("ck_property_policy__ladder", "\"priority_ladder\" IS NULL OR \"priority_ladder\" <@ ARRAY['SOLD_TONIGHT', 'DEPARTURE', 'DAILY', 'REFRESH']::text[]");

                            t.HasCheckConstraint("ck_property_policy__linen_rule", "\"linen_rule_kind\" IN ('EVERY_N_DEFERRABLE', 'MUST_BY_N')");

                            t.HasCheckConstraint("ck_property_policy__numbers", "linen_every_days > 0 AND refresh_after_days > 0 AND dnd_recheck_minutes > 0 AND supervisor_after_days > 0");

                            t.HasCheckConstraint("ck_property_policy__on_departure", "\"on_departure_condition\" IN ('DIRTY')");

                            t.HasCheckConstraint("ck_property_policy__states_view", "\"states_default_view\" IN ('SHEET', 'TAP_GRID', 'COMPACT')");

                            t.HasCheckConstraint("ck_property_policy__stay_source", "\"stay_source\" IN ('PMS', 'GUESTOPS', 'MANUAL')");

                            t.HasCheckConstraint("ck_property_policy__strategy", "\"assignment_strategy\" IN ('CONTINUITY', 'SAME_ZONE', 'LOWEST_LOAD')");

                            t.HasCheckConstraint("ck_property_policy__towels", "\"towels\" IN ('DAILY', 'GREEN_PROGRAMME')");

                            t.HasCheckConstraint("ck_property_policy__trigger_mode", "\"trigger_mode\" IN ('PREPARE', 'AUTOMATIC')");

                            t.HasCheckConstraint("ck_property_policy__unsold", "\"unsold_departure\" IN ('TODAY', 'MAY_WAIT')");

                            t.HasCheckConstraint("ck_property_policy__who_leads", "\"who_leads\" IN ('ROOM_CARE', 'PMS')");
                        });
                });

            modelBuilder.Entity("HotelOS.RoomCare.Domain.Restock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<Guid>("ByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("by_user_id");

                    b.Property<string>("Items")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("items");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<Guid?>("StayId")
                        .HasColumnType("uuid")
                        .HasColumnName("stay_id");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.HasKey("Id")
                        .HasName("pk_restock");

                    b.HasIndex("PropertyId", "RoomId", "At")
                        .HasDatabaseName("ix_restock_property_id_room_id_at");

                    b.ToTable("restock", "roomcare");
                });

            modelBuilder.Entity("HotelOS.RoomCare.Domain.RoomCareManagerGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid>("GrantedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid?>("RevokedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("revoked_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_roomcare_manager_grant");

                    b.HasIndex("PropertyId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_roomcare_manager_grant_property_id_user_id")
                        .HasFilter("revoked_at IS NULL");

                    b.ToTable("roomcare_manager_grant", "roomcare");
                });

            modelBuilder.Entity("HotelOS.RoomCare.Domain.RoomObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Applied")
                        .HasColumnType("boolean")
                        .HasColumnName("applied");

                    b.Property<Guid?>("ByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("by_user_id");

                    b.Property<string>("Condition")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("condition");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<bool?>("IsPseudoRoom")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pseudo_room");

                    b.Property<DateTimeOffset?>("NextSoldAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_sold_at");

                    b.Property<string>("Occupancy")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("occupancy");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<DateOnly?>("OperatingDay")
                        .HasColumnType("date")
                        .HasColumnName("operating_day");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("outcome");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("source");

                    b.PrimitiveCollection<List<string>>("StayStatuses")
                        .HasColumnType("text[]")
                        .HasColumnName("stay_statuses");

                    b.Property<string>("Via")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("via");

                    b.HasKey("Id")
                        .HasName("pk_room_observation");

                    b.HasIndex("EventId", "RoomId")
                        .IsUnique()
                        .HasDatabaseName("ix_room_observation_event_id_room_id")
                        .HasFilter("event_id IS NOT NULL");

                    b.HasIndex("PropertyId", "RoomId", "OccurredAt")
                        .HasDatabaseName("ix_room_observation_property_id_room_id_occurred_at");

                    b.ToTable("room_observation", "roomcare", t =>
                        {
                            t.HasCheckConstraint("ck_room_observation__condition", "\"condition\" IS NULL OR \"condition\" IN ('DIRTY', 'CLEAN', 'INSPECTED')");

                            t.HasCheckConstraint("ck_room_observation__manual_has_person", "source <> 'MANUAL' OR by_user_id IS NOT NULL");

                            t.HasCheckConstraint("ck_room_observation__occupancy", "\"occupancy\" IS NULL OR \"occupancy\" IN ('VACANT', 'OCCUPIED', 'UNKNOWN')");

                            t.HasCheckConstraint("ck_room_observation__outcome", "\"outcome\" IN ('APPLIED', 'OLDER_THAN_ACT', 'DISAGREEMENT_FLAGGED', 'APPLIED_PMS_LEADS')");

                            t.HasCheckConstraint("ck_room_observation__source", "\"source\" IN ('PMS', 'GUESTOPS', 'MANUAL', 'ENGINEERING', 'SYSTEM')");

                            t.HasCheckConstraint("ck_room_observation__stay_statuses", "\"stay_statuses\" IS NULL OR \"stay_statuses\" <@ ARRAY['BOOKED', 'CHECKED_IN', 'CHECKED_OUT', 'CANCELLED', 'NO_SHOW', 'DUE_OUT', 'WAITLISTED', 'PENDING']::text[]");

                            t.HasCheckConstraint("ck_room_observation__via", "\"via\" IS NULL OR \"via\" IN ('APP', 'HOSPILOT')");
                        });
                });

            modelBuilder.Entity("HotelOS.RoomCare.Domain.RoomState", b =>
                {
                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("condition");

                    b.Property<DateTimeOffset>("ConditionSetAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("condition_set_at");

                    b.Property<Guid?>("ConditionSetById")
                        .HasColumnType("uuid")
                        .HasColumnName("condition_set_by_id");

                    b.Property<string>("ConditionSetByKind")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("condition_set_by_kind");

                    b.Property<string>("ConditionSource")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("condition_source");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DaysCountedThrough")
                        .HasColumnType("date")
                        .HasColumnName("days_counted_through");

                    b.Property<int>("DaysWithoutService")
                        .HasColumnType("integer")
                        .HasColumnName("days_without_service");

                    b.Property<DateTimeOffset?>("DisagreementClearedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disagreement_cleared_at");

                    b.Property<Guid?>("DisagreementClearedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("disagreement_cleared_by");

                    b.Property<string>("DisagreementClearedKept")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("disagreement_cleared_kept");

                    b.Property<DateTimeOffset?>("DisagreementObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disagreement_observed_at");

                    b.Property<string>("DisagreementObservedCondition")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("disagreement_observed_condition");

                    b.Property<string>("DisagreementSource")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("disagreement_source");

                    b.Property<bool>("IsPseudoRoom")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pseudo_room");

                    b.Property<DateTimeOffset?>("LastObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_observed_at");

                    b.Property<DateOnly?>("LinenLastChangedOn")
                        .HasColumnType("date")
                        .HasColumnName("linen_last_changed_on");

                    b.Property<DateTimeOffset?>("NextSoldAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_sold_at");

                    b.Property<string>("Occupancy")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("occupancy");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.PrimitiveCollection<List<string>>("StayStatuses")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("stay_statuses");

                    b.Property<DateOnly?>("SupervisedSince")
                        .HasColumnType("date")
                        .HasColumnName("supervised_since");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("RoomId")
                        .HasName("pk_room_state");

                    b.HasIndex("PropertyId", "Condition")
                        .HasDatabaseName("ix_room_state_property_id_condition");

                    b.ToTable("room_state", "roomcare", t =>
                        {
                            t.HasCheckConstraint("ck_room_state__condition", "\"condition\" IN ('DIRTY', 'CLEAN', 'INSPECTED')");

                            t.HasCheckConstraint("ck_room_state__days_without_service", "days_without_service >= 0");

                            t.HasCheckConstraint("ck_room_state__disagreement_condition", "\"disagreement_observed_condition\" IS NULL OR \"disagreement_observed_condition\" IN ('DIRTY', 'CLEAN', 'INSPECTED')");

                            t.HasCheckConstraint("ck_room_state__disagreement_kept", "\"disagreement_cleared_kept\" IS NULL OR \"disagreement_cleared_kept\" IN ('OURS', 'THEIRS')");

                            t.HasCheckConstraint("ck_room_state__disagreement_source", "\"disagreement_source\" IS NULL OR \"disagreement_source\" IN ('PMS', 'GUESTOPS', 'MANUAL', 'ENGINEERING', 'SYSTEM')");

                            t.HasCheckConstraint("ck_room_state__occupancy", "\"occupancy\" IN ('VACANT', 'OCCUPIED', 'UNKNOWN')");

                            t.HasCheckConstraint("ck_room_state__set_by_kind", "\"condition_set_by_kind\" IN ('USER', 'SYSTEM', 'APPLICATION')");

                            t.HasCheckConstraint("ck_room_state__source", "\"condition_source\" IN ('ATTENDANT', 'INSPECTION', 'SUPERVISOR', 'PMS', 'GUESTOPS', 'MANUAL', 'SYSTEM')");

                            t.HasCheckConstraint("ck_room_state__stay_statuses", "\"stay_statuses\" IS NULL OR \"stay_statuses\" <@ ARRAY['BOOKED', 'CHECKED_IN', 'CHECKED_OUT', 'CANCELLED', 'NO_SHOW', 'DUE_OUT', 'WAITLISTED', 'PENDING']::text[]");
                        });
                });

            modelBuilder.Entity("HotelOS.RoomCare.Domain.RoomSupervision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<Guid?>("DecidedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by_user_id");

                    b.Property<string>("Decision")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("decision");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<DateOnly>("OperatingDay")
                        .HasColumnType("date")
                        .HasColumnName("operating_day");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("reason");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.HasKey("Id")
                        .HasName("pk_room_supervision");

                    b.HasIndex("PropertyId", "DecidedAt")
                        .HasDatabaseName("ix_room_supervision_property_id_decided_at");

                    b.HasIndex("PropertyId", "RoomId", "OperatingDay", "Reason")
                        .IsUnique()
                        .HasDatabaseName("ix_room_supervision_property_id_room_id_operating_day_reason");

                    b.ToTable("room_supervision", "roomcare", t =>
                        {
                            t.HasCheckConstraint("ck_room_supervision__decision", "\"decision\" IS NULL OR \"decision\" IN ('DND_APPROVED', 'CLEAN', 'OTHER')");

                            t.HasCheckConstraint("ck_room_supervision__decision_complete", "(decision IS NULL) = (decided_at IS NULL) AND (decision IS NULL) = (decided_by_user_id IS NULL)");

                            t.HasCheckConstraint("ck_room_supervision__reason", "\"reason\" IN ('DAYS_WITHOUT_SERVICE', 'DISAGREEMENT', 'ARRIVAL_BEFORE_WINDOW', 'NOBODY_AVAILABLE')");
                        });
                });

            modelBuilder.Entity("HotelOS.RoomCare.Domain.RoomTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to_user_id");

                    b.Property<string>("ChecklistRef")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("checklist_ref");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Credits")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("credits");

                    b.Property<string>("DecidedBy")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("decided_by");

                    b.Property<string>("DecisionInputs")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("decision_inputs");

                    b.Property<Guid?>("DecisionRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("decision_run_id");

                    b.Property<DateTimeOffset?>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<DateTimeOffset?>("EarliestAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("earliest_at");

                    b.Property<int>("ExtraMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("extra_minutes");

                    b.Property<string>("InspectionRule")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("inspection_rule");

                    b.Property<string>("LinenDue")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("linen_due");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<int>("MinutesExpected")
                        .HasColumnType("integer")
                        .HasColumnName("minutes_expected");

                    b.Property<DateOnly>("OperatingDay")
                        .HasColumnType("date")
                        .HasColumnName("operating_day");

                    b.Property<string>("Outcome")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("outcome");

                    b.PrimitiveCollection<List<string>>("PartialDone")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("partial_done");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("priority");

                    b.Property<int>("PriorityRank")
                        .HasColumnType("integer")
                        .HasColumnName("priority_rank");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<string>("Reduction")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("reduction");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("service");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<string>("Window")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("window");

                    b.HasKey("Id")
                        .HasName("pk_room_task");

                    b.HasIndex("PropertyId", "AssignedToUserId", "Status")
                        .HasDatabaseName("ix_room_task_property_id_assigned_to_user_id_status");

                    b.HasIndex("PropertyId", "OperatingDay", "Status")
                        .HasDatabaseName("ix_room_task_property_id_operating_day_status");

                    b.HasIndex("PropertyId", "LocationId", "OperatingDay", "Window", "Service", "DueAt")
                        .IsUnique()
                        .HasDatabaseName("ix_room_task_property_id_location_id_operating_day_window_serv");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("PropertyId", "LocationId", "OperatingDay", "Window", "Service", "DueAt"), false);

                    b.ToTable("room_task", "roomcare", t =>
                        {
                            t.HasCheckConstraint("ck_room_task__area_or_room", "(service = 'AREA_CLEAN') = (room_id IS NULL)");

                            t.HasCheckConstraint("ck_room_task__decided_by", "\"decided_by\" IN ('PREPARE', 'AUTOMATIC', 'SUPERVISOR', 'SYSTEM')");

                            t.HasCheckConstraint("ck_room_task__ended_has_outcome", "status NOT IN ('ENDED', 'CLOSED_BY_POLICY') OR outcome IS NOT NULL");

                            t.HasCheckConstraint("ck_room_task__inspection_rule", "\"inspection_rule\" IN ('NONE', 'ALWAYS', 'ARRIVALS', 'EVERY_NTH', 'VIP')");

                            t.HasCheckConstraint("ck_room_task__linen_due", "\"linen_due\" IN ('NOT_DUE', 'DUE', 'MUST')");

                            t.HasCheckConstraint("ck_room_task__minutes", "minutes_expected >= 0 AND extra_minutes >= 0");

                            t.HasCheckConstraint("ck_room_task__outcome", "\"outcome\" IS NULL OR \"outcome\" IN ('DONE', 'PARTIAL', 'DECLINED', 'DND', 'SKIPPED_BY_GUEST', 'NOT_REACHED', 'SUPERVISOR_DND_APPROVED', 'SUPERVISOR_CLEANED', 'SUPERVISOR_DECIDED')");

                            t.HasCheckConstraint("ck_room_task__partial_done", "\"partial_done\" IS NULL OR \"partial_done\" <@ ARRAY['BATHROOM', 'TOWELS', 'RUBBISH', 'BED']::text[]");

                            t.HasCheckConstraint("ck_room_task__priority", "\"priority\" IN ('SOLD_TONIGHT', 'DEPARTURE', 'DAILY', 'REFRESH')");

                            t.HasCheckConstraint("ck_room_task__service", "\"service\" IN ('DEPARTURE_CLEAN', 'DAILY_SERVICE', 'TURNDOWN', 'REFRESH', 'AREA_CLEAN')");

                            t.HasCheckConstraint("ck_room_task__status", "\"status\" IN ('PENDING_POLICY', 'PLANNED', 'ASSIGNED', 'IN_PROGRESS', 'ENDED', 'CLOSED_BY_POLICY')");

                            t.HasCheckConstraint("ck_room_task__window", "\"window\" IN ('MORNING', 'EVENING')");
                        });
                });

            modelBuilder.Entity("HotelOS.RoomCare.Domain.RoomZoneAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveUntil")
                        .HasColumnType("date")
                        .HasColumnName("effective_until");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uuid")
                        .HasColumnName("zone_id");

                    b.HasKey("Id")
                        .HasName("pk_room_zone_assignment");

                    b.HasIndex("PropertyId", "RoomId")
                        .IsUnique()
                        .HasDatabaseName("ix_room_zone_assignment_property_id_room_id")
                        .HasFilter("effective_until IS NULL");

                    b.HasIndex("PropertyId", "ZoneId")
                        .HasDatabaseName("ix_room_zone_assignment_property_id_zone_id");

                    b.ToTable("room_zone_assignment", "roomcare", t =>
                        {
                            t.HasCheckConstraint("ck_room_zone_assignment__order", "effective_until IS NULL OR effective_from <= effective_until");
                        });
                });

            modelBuilder.Entity("HotelOS.RoomCare.Domain.ServiceStandard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChecklistRef")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("checklist_ref");

                    b.Property<decimal>("Credits")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("credits");

                    b.Property<string>("InspectionRule")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("inspection_rule");

                    b.Property<int>("Minutes")
                        .HasColumnType("integer")
                        .HasColumnName("minutes");

                    b.PrimitiveCollection<List<string>>("Phases")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("phases");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<Guid?>("RoomTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_type_id");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("service");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_service_standard");

                    b.HasIndex("PropertyId", "RoomTypeId", "Service")
                        .IsUnique()
                        .HasDatabaseName("ix_service_standard_property_id_room_type_id_service");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("PropertyId", "RoomTypeId", "Service"), false);

                    b.ToTable("service_standard", "roomcare", t =>
                        {
                            t.HasCheckConstraint("ck_service_standard__inspection_rule", "\"inspection_rule\" IN ('NONE', 'ALWAYS', 'ARRIVALS', 'EVERY_NTH', 'VIP')");

                            t.HasCheckConstraint("ck_service_standard__minutes", "minutes >= 0 AND credits >= 0");

                            t.HasCheckConstraint("ck_service_standard__phases", "\"phases\" IS NULL OR \"phases\" <@ ARRAY['STRIP', 'CLEAN', 'MAKE_UP', 'DONE', 'INSPECT']::text[]");

                            t.HasCheckConstraint("ck_service_standard__service", "\"service\" IN ('DEPARTURE_CLEAN', 'DAILY_SERVICE', 'TURNDOWN', 'REFRESH', 'AREA_CLEAN')");
                        });
                });

            modelBuilder.Entity("HotelOS.RoomCare.Domain.ServiceWindow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowAssignmentOutside")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_assignment_outside");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<TimeOnly>("Ends")
                        .HasColumnType("time without time zone")
                        .HasColumnName("ends");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<TimeOnly>("Starts")
                        .HasColumnType("time without time zone")
                        .HasColumnName("starts");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<string>("Window")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("window");

                    b.HasKey("Id")
                        .HasName("pk_service_window");

                    b.HasIndex("PropertyId", "Window")
                        .IsUnique()
                        .HasDatabaseName("ix_service_window_property_id_window");

                    b.ToTable("service_window", "roomcare", t =>
                        {
                            t.HasCheckConstraint("ck_service_window__not_empty", "starts <> ends");

                            t.HasCheckConstraint("ck_service_window__window", "\"window\" IN ('MORNING', 'EVENING')");
                        });
                });

            modelBuilder.Entity("HotelOS.RoomCare.Domain.ShiftPresence", b =>
                {
                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<string>("DepartmentCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("department_code");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<int>("OnNow")
                        .HasColumnType("integer")
                        .HasColumnName("on_now");

                    b.HasKey("PropertyId", "DepartmentCode")
                        .HasName("pk_shift_presence");

                    b.ToTable("shift_presence", "roomcare");
                });

            modelBuilder.Entity("HotelOS.RoomCare.Domain.TaskAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid?>("AssignedById")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by_id");

                    b.Property<string>("AssignedByKind")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("assigned_by_kind");

                    b.Property<string>("EndReason")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("end_reason");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("mode");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Via")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("via");

                    b.HasKey("Id")
                        .HasName("pk_task_assignment");

                    b.HasIndex("TaskId")
                        .IsUnique()
                        .HasDatabaseName("ix_task_assignment_task_id")
                        .HasFilter("ended_at IS NULL");

                    b.HasIndex("PropertyId", "UserId", "EndedAt")
                        .HasDatabaseName("ix_task_assignment_property_id_user_id_ended_at");

                    b.ToTable("task_assignment", "roomcare", t =>
                        {
                            t.HasCheckConstraint("ck_task_assignment__by_kind", "\"assigned_by_kind\" IN ('USER', 'SYSTEM', 'APPLICATION')");

                            t.HasCheckConstraint("ck_task_assignment__end_pair", "(ended_at IS NULL) = (end_reason IS NULL)");

                            t.HasCheckConstraint("ck_task_assignment__end_reason", "\"end_reason\" IS NULL OR \"end_reason\" IN ('REASSIGNED', 'ENDED', 'SHIFT_ENDED', 'STAFF_EXITED')");

                            t.HasCheckConstraint("ck_task_assignment__mode", "\"mode\" IN ('PROPOSED', 'ACCEPTED', 'MANUAL')");

                            t.HasCheckConstraint("ck_task_assignment__via", "\"via\" IN ('APP', 'HOSPILOT')");
                        });
                });

            modelBuilder.Entity("HotelOS.RoomCare.Domain.TaskAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<Guid>("ByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("by_user_id");

                    b.Property<string>("Found")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("found");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("note");

                    b.PrimitiveCollection<List<string>>("PartialDone")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("partial_done");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.HasKey("Id")
                        .HasName("pk_task_attempt");

                    b.HasIndex("TaskId", "At")
                        .HasDatabaseName("ix_task_attempt_task_id_at");

                    b.ToTable("task_attempt", "roomcare", t =>
                        {
                            t.HasCheckConstraint("ck_task_attempt__found", "\"found\" IN ('DONE', 'PARTIAL', 'DECLINED', 'DND')");

                            t.HasCheckConstraint("ck_task_attempt__partial_done", "\"partial_done\" IS NULL OR \"partial_done\" <@ ARRAY['BATHROOM', 'TOWELS', 'RUBBISH', 'BED']::text[]");
                        });
                });

            modelBuilder.Entity("HotelOS.RoomCare.Domain.TaskHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<Guid?>("ById")
                        .HasColumnType("uuid")
                        .HasColumnName("by_id");

                    b.Property<string>("ByKind")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("by_kind");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("from_status");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("kind");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<string>("ToStatus")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("to_status");

                    b.Property<string>("Via")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("via");

                    b.HasKey("Id")
                        .HasName("pk_task_history");

                    b.HasIndex("TaskId", "At")
                        .HasDatabaseName("ix_task_history_task_id_at");

                    b.ToTable("task_history", "roomcare", t =>
                        {
                            t.HasCheckConstraint("ck_task_history__by_kind", "\"by_kind\" IN ('USER', 'SYSTEM', 'APPLICATION')");

                            t.HasCheckConstraint("ck_task_history__kind", "\"kind\" IN ('TRANSITION', 'REDUCTION', 'REPRIORITISED', 'SUPERVISOR_DECISION', 'DISAGREEMENT_CLEARED', 'EXTRA_TIME')");

                            t.HasCheckConstraint("ck_task_history__via", "\"via\" IN ('APP', 'HOSPILOT')");
                        });
                });

            modelBuilder.Entity("HotelOS.RoomCare.Domain.TaskIssue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<Guid>("ByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("by_user_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("ItemHint")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("item_hint");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid?>("MediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_id");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.HasKey("Id")
                        .HasName("pk_task_issue");

                    b.HasIndex("CorrelationId")
                        .IsUnique()
                        .HasDatabaseName("ix_task_issue_correlation_id");

                    b.HasIndex("PropertyId", "RoomId", "At")
                        .HasDatabaseName("ix_task_issue_property_id_room_id_at");

                    b.ToTable("task_issue", "roomcare");
                });

            modelBuilder.Entity("HotelOS.RoomCare.Domain.TaskJobTouch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("JobNumber")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("job_number");

                    b.Property<DateOnly>("OperatingDay")
                        .HasColumnType("date")
                        .HasColumnName("operating_day");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<string>("Summary")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("summary");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.HasKey("Id")
                        .HasName("pk_task_job_touch");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("ix_task_job_touch_event_id");

                    b.HasIndex("PropertyId", "RoomId", "OperatingDay")
                        .HasDatabaseName("ix_task_job_touch_property_id_room_id_operating_day");

                    b.ToTable("task_job_touch", "roomcare");
                });

            modelBuilder.Entity("HotelOS.RoomCare.Domain.TaskPhase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("by_user_id");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("note");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("phase");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("status");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.HasKey("Id")
                        .HasName("pk_task_phase");

                    b.HasIndex("TaskId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_task_phase_task_id_sequence");

                    b.ToTable("task_phase", "roomcare", t =>
                        {
                            t.HasCheckConstraint("ck_task_phase__phase", "\"phase\" IN ('STRIP', 'CLEAN', 'MAKE_UP', 'DONE', 'INSPECT')");

                            t.HasCheckConstraint("ck_task_phase__status", "\"status\" IN ('PENDING', 'ACTIVE', 'DONE', 'SKIPPED', 'FAILED')");
                        });
                });

            modelBuilder.Entity("HotelOS.RoomCare.Domain.TaskWorkSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EndReason")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("end_reason");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<int>("Minutes")
                        .HasColumnType("integer")
                        .HasColumnName("minutes");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_task_work_session");

                    b.HasIndex("TaskId")
                        .IsUnique()
                        .HasDatabaseName("ix_task_work_session_task_id")
                        .HasFilter("ended_at IS NULL");

                    b.HasIndex("PropertyId", "UserId", "EndedAt")
                        .HasDatabaseName("ix_task_work_session_property_id_user_id_ended_at");

                    b.ToTable("task_work_session", "roomcare", t =>
                        {
                            t.HasCheckConstraint("ck_task_work_session__end_reason", "\"end_reason\" IS NULL OR \"end_reason\" IN ('PAUSE', 'END', 'REASSIGNED')");
                        });
                });

            modelBuilder.Entity("HotelOS.RoomCare.Infrastructure.ReadModels.MasterDataDepartment", b =>
                {
                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.ToTable("departments", "masterdata", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("HotelOS.RoomCare.Infrastructure.ReadModels.MasterDataLocation", b =>
                {
                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.ToTable("locations", "masterdata", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("HotelOS.RoomCare.Infrastructure.ReadModels.MasterDataProperty", b =>
                {
                    b.Property<TimeOnly>("BusinessDayBoundary")
                        .HasColumnType("time without time zone")
                        .HasColumnName("business_day_boundary");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.ToTable("properties", "masterdata", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("HotelOS.RoomCare.Infrastructure.ReadModels.MasterDataRoom", b =>
                {
                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("room_number");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_type_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.ToTable("rooms", "masterdata", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("HotelOS.RoomCare.Infrastructure.ReadModels.MasterDataRoomType", b =>
                {
                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.ToTable("room_types", "masterdata", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("HotelOS.RoomCare.Infrastructure.ReadModels.MasterDataStaff", b =>
                {
                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.ToTable("staff", "masterdata", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("HotelOS.RoomCare.Infrastructure.ReadModels.MasterDataZone", b =>
                {
                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.ToTable("zones", "masterdata", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
