// <auto-generated />
using System;
using System.Text.Json;
using HotelOS.Workforce.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HotelOS.Workforce.Infrastructure.Migrations
{
    [DbContext(typeof(WorkforceDbContext))]
    [Migration("20260904061703_TeamsAndShiftBoundaries")]
    partial class TeamsAndShiftBoundaries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("workforce")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HotelOS.Platform.PublishQueueEntry", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("EventId")
                        .HasName("pk_publish_state");

                    b.ToTable("publish_state", "event_store", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("HotelOS.Platform.StoredEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<int>("ActorType")
                        .HasColumnType("integer")
                        .HasColumnName("actor_type");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("aggregate_type");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("EntityVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_version");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<JsonDocument>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("session_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trace_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("EventId")
                        .HasName("pk_events");

                    b.ToTable("events", "event_store", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("HotelOS.Workforce.Domain.AttendanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("date")
                        .HasColumnName("business_date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_reference");

                    b.Property<TimeOnly?>("InAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("in_at");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<TimeOnly?>("OutAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("out_at");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<Guid?>("RecordedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by_user_id");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_attendance");

                    b.HasIndex("PropertyId", "BusinessDate")
                        .HasDatabaseName("ix_attendance__property_date");

                    b.HasIndex("PropertyId", "StaffId", "BusinessDate")
                        .IsUnique()
                        .HasDatabaseName("uq_attendance__property_staff_date");

                    b.ToTable("attendance", "workforce", t =>
                        {
                            t.HasCheckConstraint("ck_attendance__out_needs_in", "out_at IS NULL OR in_at IS NOT NULL");

                            t.HasCheckConstraint("ck_attendance__provenance", "(source = 0 AND recorded_by_user_id IS NOT NULL) OR (source <> 0 AND external_reference IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("HotelOS.Workforce.Domain.Capability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateOnly?>("ValidUntil")
                        .HasColumnType("date")
                        .HasColumnName("valid_until");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_capabilities");

                    b.HasIndex("PropertyId", "ValidUntil")
                        .HasDatabaseName("ix_capabilities__property_expiry")
                        .HasFilter("valid_until IS NOT NULL");

                    b.HasIndex("PropertyId", "StaffId", "Name")
                        .IsUnique()
                        .HasDatabaseName("uq_capabilities__property_staff_name");

                    b.ToTable("capabilities", "workforce", t =>
                        {
                            t.HasCheckConstraint("ck_capabilities__name_present", "length(btrim(name)) > 0");
                        });
                });

            modelBuilder.Entity("HotelOS.Workforce.Domain.DutyAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DutyType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("duty_type");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<string>("HandoverNote")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("handover_note");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_id");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_duties");

                    b.HasIndex("PropertyId", "StartsAt")
                        .HasDatabaseName("ix_duties__property_start");

                    b.ToTable("duties", "workforce", t =>
                        {
                            t.HasCheckConstraint("ck_duties__span_ordered", "ends_at > starts_at");
                        });
                });

            modelBuilder.Entity("HotelOS.Workforce.Domain.LeaveLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Days")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("days");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<Guid?>("LeaveRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("leave_request_id");

                    b.Property<Guid>("LeaveTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("leave_type_id");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<DateOnly>("OccurredOn")
                        .HasColumnType("date")
                        .HasColumnName("occurred_on");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<Guid?>("RecordedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by_user_id");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_id");

                    b.HasKey("Id")
                        .HasName("pk_leave_ledger");

                    b.HasIndex("PropertyId", "StaffId", "LeaveTypeId")
                        .HasDatabaseName("ix_leave_ledger__property_staff_type");

                    b.ToTable("leave_ledger", "workforce", t =>
                        {
                            t.HasCheckConstraint("ck_leave_ledger__days_not_zero", "days <> 0");
                        });
                });

            modelBuilder.Entity("HotelOS.Workforce.Domain.LeaveRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApproverStaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("approver_staff_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<string>("DecisionNote")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("decision_note");

                    b.Property<Guid?>("EnteredByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("entered_by_user_id");

                    b.Property<DateOnly>("From")
                        .HasColumnType("date")
                        .HasColumnName("leave_from");

                    b.Property<Guid>("LeaveTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("leave_type_id");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_id");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<DateOnly>("To")
                        .HasColumnType("date")
                        .HasColumnName("leave_to");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_leave_requests");

                    b.HasIndex("PropertyId", "ApproverStaffId", "State")
                        .HasDatabaseName("ix_leave_requests__property_approver_state");

                    b.HasIndex("PropertyId", "StaffId", "From")
                        .HasDatabaseName("ix_leave_requests__property_staff_from");

                    b.ToTable("leave_requests", "workforce", t =>
                        {
                            t.HasCheckConstraint("ck_leave_requests__range_ordered", "leave_to >= leave_from");
                        });
                });

            modelBuilder.Entity("HotelOS.Workforce.Domain.LeaveType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("AccrualPerMonth")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("accrual_per_month");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_leave_types");

                    b.HasIndex("PropertyId", "Code")
                        .IsUnique()
                        .HasDatabaseName("uq_leave_types__property_code");

                    b.ToTable("leave_types", "workforce", t =>
                        {
                            t.HasCheckConstraint("ck_leave_types__accrual_not_negative", "accrual_per_month IS NULL OR accrual_per_month >= 0");
                        });
                });

            modelBuilder.Entity("HotelOS.Workforce.Domain.Posting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("department_code");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<bool>("IsDepartmentHead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_department_head");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("JobRole")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("job_role");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<Guid?>("ReportingManagerStaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("reporting_manager_staff_id");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid?>("ZoneId")
                        .HasColumnType("uuid")
                        .HasColumnName("zone_id");

                    b.HasKey("Id")
                        .HasName("pk_postings");

                    b.HasIndex("PropertyId", "DepartmentCode")
                        .HasDatabaseName("ix_postings__property_department");

                    b.HasIndex("PropertyId", "StaffId")
                        .HasDatabaseName("ix_postings__property_staff");

                    b.HasIndex("PropertyId", "ZoneId")
                        .HasDatabaseName("ix_postings__property_zone");

                    b.ToTable("postings", "workforce", t =>
                        {
                            t.HasCheckConstraint("ck_postings__department_code_present", "length(btrim(department_code)) > 0");

                            t.HasCheckConstraint("ck_postings__window_ordered", "effective_to IS NULL OR effective_to >= effective_from");
                        });
                });

            modelBuilder.Entity("HotelOS.Workforce.Domain.ShiftAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CatalogueEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalogue_entry_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("department_code");

                    b.Property<TimeOnly?>("OverrideEndsAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("override_ends_at");

                    b.Property<TimeOnly?>("OverrideStartsAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("override_starts_at");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_shift_assignments");

                    b.HasIndex("PropertyId", "Date", "DepartmentCode")
                        .HasDatabaseName("ix_shift_assignments__property_date_department");

                    b.HasIndex("PropertyId", "StaffId", "Date")
                        .IsUnique()
                        .HasDatabaseName("uq_shift_assignments__property_staff_date");

                    b.ToTable("shift_assignments", "workforce", t =>
                        {
                            t.HasCheckConstraint("ck_shift_assignments__department_present", "length(btrim(department_code)) > 0");

                            t.HasCheckConstraint("ck_shift_assignments__override_complete", "(override_starts_at IS NULL) = (override_ends_at IS NULL)");
                        });
                });

            modelBuilder.Entity("HotelOS.Workforce.Domain.ShiftBoundary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AnnouncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("announced_at");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("date")
                        .HasColumnName("business_date");

                    b.Property<Guid>("CatalogueEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalogue_entry_id");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("department_code");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<int>("OnNowAfter")
                        .HasColumnType("integer")
                        .HasColumnName("on_now_after");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.HasKey("Id")
                        .HasName("pk_shift_boundaries");

                    b.HasIndex("PropertyId", "BusinessDate")
                        .HasDatabaseName("ix_shift_boundaries__property_date");

                    b.HasIndex("PropertyId", "DepartmentCode", "CatalogueEntryId", "BusinessDate", "Kind")
                        .IsUnique()
                        .HasDatabaseName("uq_shift_boundaries__announced_once");

                    b.ToTable("shift_boundaries", "workforce");
                });

            modelBuilder.Entity("HotelOS.Workforce.Domain.ShiftCatalogueEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("colour");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("short_code");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_shift_catalogue");

                    b.HasIndex("PropertyId", "ShortCode")
                        .IsUnique()
                        .HasDatabaseName("uq_shift_catalogue__property_code")
                        .HasFilter("active");

                    b.ToTable("shift_catalogue", "workforce", t =>
                        {
                            t.HasCheckConstraint("ck_shift_catalogue__code_present", "length(btrim(short_code)) > 0");
                        });
                });

            modelBuilder.Entity("HotelOS.Workforce.Domain.ShiftHours", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CatalogueEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalogue_entry_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<TimeOnly?>("EndsAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("ends_at");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<TimeOnly?>("SecondEndsAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("second_ends_at");

                    b.Property<TimeOnly?>("SecondStartsAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("second_starts_at");

                    b.Property<TimeOnly?>("StartsAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("starts_at");

                    b.HasKey("Id")
                        .HasName("pk_shift_hours");

                    b.HasIndex("CatalogueEntryId")
                        .IsUnique()
                        .HasDatabaseName("uq_shift_hours__one_open_revision")
                        .HasFilter("effective_to IS NULL");

                    b.HasIndex("CatalogueEntryId", "EffectiveFrom")
                        .HasDatabaseName("ix_shift_hours__entry_from");

                    b.ToTable("shift_hours", "workforce", t =>
                        {
                            t.HasCheckConstraint("ck_shift_hours__second_needs_first", "second_starts_at IS NULL OR starts_at IS NOT NULL");

                            t.HasCheckConstraint("ck_shift_hours__second_span_complete", "(second_starts_at IS NULL) = (second_ends_at IS NULL)");

                            t.HasCheckConstraint("ck_shift_hours__second_span_not_empty", "second_starts_at IS NULL OR second_starts_at <> second_ends_at");

                            t.HasCheckConstraint("ck_shift_hours__span_complete", "(starts_at IS NULL) = (ends_at IS NULL)");

                            t.HasCheckConstraint("ck_shift_hours__span_not_empty", "starts_at IS NULL OR starts_at <> ends_at");

                            t.HasCheckConstraint("ck_shift_hours__window_ordered", "effective_to IS NULL OR effective_to >= effective_from");
                        });
                });

            modelBuilder.Entity("HotelOS.Workforce.Domain.SwapProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<Guid?>("ApproverStaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("approver_staff_id");

                    b.Property<Guid>("ColleagueAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("colleague_assignment_id");

                    b.Property<Guid>("ColleagueStaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("colleague_staff_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<string>("DecisionNote")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("decision_note");

                    b.Property<Guid?>("EnteredByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("entered_by_user_id");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<Guid>("ProposerAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("proposer_assignment_id");

                    b.Property<Guid>("ProposerStaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("proposer_staff_id");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_swap_proposals");

                    b.HasIndex("PropertyId", "State", "ApproverStaffId")
                        .HasDatabaseName("ix_swap_proposals__property_state_approver");

                    b.HasIndex("PropertyId", "State", "ColleagueStaffId")
                        .HasDatabaseName("ix_swap_proposals__property_state_colleague");

                    b.ToTable("swap_proposals", "workforce", t =>
                        {
                            t.HasCheckConstraint("ck_swap_proposals__two_people", "proposer_staff_id <> colleague_staff_id");
                        });
                });

            modelBuilder.Entity("HotelOS.Workforce.Domain.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("department_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_teams");

                    b.HasIndex("PropertyId", "DepartmentCode")
                        .HasDatabaseName("ix_teams__property_department");

                    b.HasIndex("PropertyId", "DepartmentCode", "Name")
                        .IsUnique()
                        .HasDatabaseName("uq_teams__property_department_name")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("teams", "workforce", t =>
                        {
                            t.HasCheckConstraint("ck_teams__department_code_present", "length(btrim(department_code)) > 0");

                            t.HasCheckConstraint("ck_teams__name_present", "length(btrim(name)) > 0");
                        });
                });

            modelBuilder.Entity("HotelOS.Workforce.Domain.TeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("JoinedOn")
                        .HasColumnType("date")
                        .HasColumnName("joined_on");

                    b.Property<DateOnly?>("LeftOn")
                        .HasColumnType("date")
                        .HasColumnName("left_on");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_id");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_team_members");

                    b.HasIndex("PropertyId", "StaffId")
                        .HasDatabaseName("ix_team_members__property_staff");

                    b.HasIndex("PropertyId", "TeamId")
                        .HasDatabaseName("ix_team_members__property_team");

                    b.HasIndex("TeamId", "StaffId")
                        .IsUnique()
                        .HasDatabaseName("uq_team_members__team_staff_live")
                        .HasFilter("left_on IS NULL");

                    b.ToTable("team_members", "workforce", t =>
                        {
                            t.HasCheckConstraint("ck_team_members__window_ordered", "left_on IS NULL OR left_on >= joined_on");
                        });
                });

            modelBuilder.Entity("HotelOS.Workforce.Domain.WorkforcePolicy", b =>
                {
                    b.Property<Guid>("PropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("OvertimeDailyHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("overtime_daily_hours");

                    b.Property<decimal?>("OvertimeWeeklyHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("overtime_weekly_hours");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("PropertyId")
                        .HasName("pk_policies");

                    b.ToTable("policies", "workforce", t =>
                        {
                            t.HasCheckConstraint("ck_policies__overtime_daily_positive", "overtime_daily_hours IS NULL OR overtime_daily_hours > 0");

                            t.HasCheckConstraint("ck_policies__overtime_weekly_positive", "overtime_weekly_hours IS NULL OR overtime_weekly_hours > 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
