#!/usr/bin/env python3
"""Run the platform's standards checks against THIS repository.

WHY THIS EXISTS
---------------
``check_source_standards.py``, ``check_documentation.py`` and
``check_rulings_recorded.py`` all resolve their root from ``__file__``::

    ROOT = Path(__file__).resolve().parent.parent

So each one walks the repository it lives in, **whatever directory it is run
from**, and every one of them lives in HosPilotOS.  Measured 2026-09-24: run
from this repository's root, ``check_source_standards.py`` examined **zero**
files here and reported on the platform's.  Every "standards PASS" any round
has ever quoted for an installable application was a statement about the other
repository.

It is ADR 0168's sibling.  Not a missing rule — a population defined by where
the tool happens to live, which is the same shape as a consumer list that stops
at the repository boundary.

NOTHING HERE REIMPLEMENTS A CHECK
---------------------------------
The counting, the limit, the question matcher, the range resolver and the
parent-row rule are **imported from the platform's own scripts**, so the
numbers mean what the tool means and a change there arrives here.

**That is not a preference, and the first draft of this file proved it.**  A
hand-written question matcher reported four Workforce numbers as cited-but-
unrecorded — ``WF-Q3``, ``WF-Q4``, ``WF-Q12``, ``WF-Q14``.  All four are
covered by the register's ``WF-Q1–Q6`` and ``WF-Q11–Q15`` range rows, which
``recorded()`` resolves and a regular expression does not.  Four false
accusations against a colleague's shipped code, from a detector written by
somebody who had just read the real one.

THE EXCLUSIONS ARE DERIVED, NEVER LISTED
----------------------------------------
A hand-kept exemption list is how a guard dies: each entry is individually
reasonable, nobody ever removes one, and within a month the rule covers the
cases nobody was going to get wrong.

Two derivations, and each is read from the artefact or from git:

``git check-ignore``
    Catches every built bundle and staged payload — ``ui/module.js``,
    ``ui/preview/frame.js``, ``ui/widgets/*.js``, ``.build/payload/**``.
    Verified 2026-09-24: all of them ignored.  **A build output is excluded
    because the repository already says it is not source**, not because
    somebody typed its path here.

``<auto-generated>``
    The file's own declaration.  EF Core's ``*.Designer.cs`` and
    ``*ModelSnapshot.cs`` carry it in their first lines; the migration body
    beside them does not, and is reached through the sibling that does.

**The architect's own measurement used a hand-written skip set** — ``obj``,
``bin``, ``target``, ``node_modules``, ``dist``, ``build``, ``.venv``,
``__pycache__`` — and reported 1105 files.  This derives 1113.  The eight are
not defended; the derived population is the baseline.

THE DENOMINATOR IS ASSERTED
---------------------------
A walk that quietly stopped finding things would pass every check below on the
shrinking set it still had, and a zero from it reads as *nothing is wrong*
rather than *nothing was measured*.  ``FLOOR`` is what makes that impossible,
and it is a floor rather than an equality so adding an application does not
fail the build.

USAGE
-----
::

    python scripts/check_standards.py
    python scripts/check_standards.py --json

    exit 0   every check passed
    exit 1   a check failed, and it says which
    exit 2   the tool could not run — the platform repository was not found

**An absent platform repository reports UNVERIFIED and exits 2.**  It is not a
pass.  ADR 0168 ruled exactly this for the consumer check: *"an unavailable
sibling reports UNVERIFIED — which is not PASS and BLOCKS phase-close."*
"""

from __future__ import annotations

import importlib.util
import json
import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

#: The lowest number of source files this repository has ever held, rounded
#: down. Measured 1113 on 2026-09-24 across five applications and one
#: connector. A walk returning fewer has stopped finding things.
FLOOR = 1000

#: Read from the file's own first lines. Roslyn and EF Core both emit it.
GENERATED = re.compile(r"auto-?generated", re.IGNORECASE)

#: How far in to look for that declaration. Long enough for a licence header,
#: short enough that the word appearing in a comment halfway down a real file
#: cannot exempt it.
DECLARATION_BYTES = 600


def platform_root() -> Path | None:
    """The platform repository, or None.

    Named by ``HOTELOS_PLATFORM`` where a machine puts it somewhere else;
    otherwise the sibling, which is where ADR 0168's own consumer check looks.
    """
    stated = os.environ.get("HOTELOS_PLATFORM")
    if stated:
        candidate = Path(stated).expanduser().resolve()
        return candidate if (candidate / "docs" / "decisions").is_dir() else None

    sibling = ROOT.parent / "HosPilotOS"
    return sibling if (sibling / "docs" / "decisions").is_dir() else None


def load(platform: Path, name: str):
    """Import a platform script by path, without installing anything."""
    spec = importlib.util.spec_from_file_location(name, platform / "scripts" / f"{name}.py")
    if spec is None or spec.loader is None:
        raise ImportError(f"could not load {name} from {platform}")

    module = importlib.util.module_from_spec(spec)

    # **Registered before it is executed.** `@dataclass` resolves its class's
    # module through `sys.modules` while the class body is being processed, so
    # a module absent from there fails with an `AttributeError` about
    # `NoneType.__dict__` — three frames deep in `dataclasses`, naming nothing
    # that would send a reader here.
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


def ignored_paths() -> tuple[set[str], tuple[str, ...]]:
    """What git ignores, as an exact set and a directory prefix tuple.

    **``--directory`` is what makes this finish.** Without it git lists every
    ignored FILE, which on a tree carrying ``node_modules`` is tens of
    thousands — and a membership test against that set, run once per source
    file, took the whole check past two minutes. With it, an ignored directory
    collapses to one entry and the prefixes stay in the low hundreds.

    A check nobody waits for is a check nobody runs, which is the same way a
    guard dies as an exemption list nobody removes an entry from.
    """
    listing = subprocess.run(
        ["git", "ls-files", "--others", "--ignored", "--exclude-standard", "--directory"],
        cwd=ROOT, capture_output=True, text=True, check=False)

    entries = [line.strip() for line in listing.stdout.splitlines() if line.strip()]

    # git marks a directory by the trailing slash it prints.
    directories = tuple(e for e in entries if e.endswith("/"))
    files = {e for e in entries if not e.endswith("/")}
    return files, directories


def declares_generated(path: Path) -> bool:
    """Whether the file says of itself that it was generated."""
    try:
        with path.open("rb") as handle:
            return GENERATED.search(handle.read(DECLARATION_BYTES).decode("utf-8", "replace")) is not None
    except OSError:
        return False


def population(suffixes: set[str]) -> tuple[list[Path], dict[str, int]]:
    """Every hand-written source file here, and what was set aside."""
    ignored_files, ignored_dirs = ignored_paths()
    kept: list[Path] = []
    aside = {"git-ignored": 0, "declares generated": 0}

    for path in sorted(ROOT.rglob("*")):
        if not path.is_file() or path.suffix.lower() not in suffixes:
            continue

        relative = path.relative_to(ROOT).as_posix()

        # `.git` itself is never listed by `ls-files`, so it is named here —
        # the one place a literal is unavoidable, and it is a directory git
        # owns rather than a file somebody chose to exclude.
        if relative.startswith(".git/"):
            continue

        if relative in ignored_files or relative.startswith(ignored_dirs):
            aside["git-ignored"] += 1
            continue

        if declares_generated(path):
            aside["declares generated"] += 1
            continue

        kept.append(path)

    return kept, aside


def over_the_ceiling(files: list[Path], std) -> list[tuple[int, str]]:
    """The files past the limit, measured by the platform's own counter."""
    found = []
    for path in files:
        try:
            lines = std.count_code_lines(path)
        except KeyError:
            # `count_code_lines` refuses a suffix it has no comment style for,
            # and says so rather than guessing. That cannot happen here — the
            # suffixes come from its own table — so a raise is a contradiction
            # worth hearing rather than swallowing.
            raise
        if lines > std.HARD_LIMIT:
            found.append((lines, path.relative_to(ROOT).as_posix()))

    return sorted(found, reverse=True)


def citations_that_resolve(platform: Path, files: list[Path]) -> dict[str, list[str]]:
    """Question numbers cited here that the platform's register never answers.

    The matcher, the range resolver and the parent rule are the register's own.
    A hand-written version of any of the three produces false accusations
    against a colleague's code — see this module's header.
    """
    rulings = load(platform, "check_rulings_recorded")
    known = rulings.recorded((platform / rulings.REGISTER).read_text(encoding="utf-8", errors="replace"))

    cited: dict[str, set[str]] = {}
    for path in files:
        text = path.read_text(encoding="utf-8", errors="replace")
        for prefix, number, suffix in set(rulings.QUESTION.findall(text)):
            cited.setdefault(f"{prefix}-Q{number}{suffix}", set()).add(
                path.relative_to(ROOT).as_posix())

    return {
        question: sorted(where)
        for question, where in cited.items()
        if question not in known and not rulings.covering_parent(question, known)
    }


def adrs_that_resolve(platform: Path, files: list[Path]) -> dict[str, list[str]]:
    """ADR numbers cited here with no such decision in the platform."""
    on_disk = {
        match.group(1)
        for decision in (platform / "docs" / "decisions").glob("*.md")
        if (match := re.match(r"^(\d{4})", decision.name))
    }

    cited: dict[str, set[str]] = {}
    for path in files:
        text = path.read_text(encoding="utf-8", errors="replace")
        for match in re.finditer(r"\bADR\s+(\d{4})\b", text):
            cited.setdefault(match.group(1), set()).add(path.relative_to(ROOT).as_posix())

    return {
        number: sorted(where)
        for number, where in cited.items()
        if number not in on_disk
    }


def main(argv: list[str]) -> int:
    as_json = "--json" in argv[1:]

    platform = platform_root()
    if platform is None:
        print("UNVERIFIED — the platform repository was not found.")
        print()
        print("  This repository's standards are the platform's, and the checks")
        print("  that define them live there. Without it nothing was measured,")
        print("  and that is not a pass (ADR 0168).")
        print()
        print("  Expected a sibling HosPilotOS, or HOTELOS_PLATFORM naming one.")
        return 2

    std = load(platform, "check_source_standards")
    files, aside = population(set(std.SUFFIXES))

    over = over_the_ceiling(files, std)
    unrecorded = citations_that_resolve(platform, files)
    unresolved = adrs_that_resolve(platform, files)

    if as_json:
        print(json.dumps({
            "schema": 1,
            "platform": str(platform),
            "files_examined": len(files),
            "set_aside": aside,
            "floor": FLOOR,
            "hard_limit": std.HARD_LIMIT,
            "over_the_limit": [{"lines": n, "file": f} for n, f in over],
            "cited_not_recorded": unrecorded,
            "adr_citations_unresolved": unresolved,
        }, indent=2))
        return 1 if (over or unrecorded or unresolved or len(files) < FLOOR) else 0

    # **The denominator first.** A clean result is read for what it MEASURED
    # before it is read for what it FOUND, and a zero without one is a claim
    # about the instrument rather than about the code.
    print(f"examined {len(files)} source files in {ROOT.name}, against {platform.name}")
    print(f"  set aside  {aside['git-ignored']} git-ignored"
          f" · {aside['declares generated']} declaring themselves generated")
    print()

    problems = 0

    if len(files) < FLOOR:
        problems += 1
        print(f"THE WALK FOUND TOO LITTLE — {len(files)}, below the floor of {FLOOR}.")
        print("  Every result below is about the set it still had. Fix this first.")
        print()

    if over:
        problems += len(over)
        print(f"OVER {std.HARD_LIMIT} CODE LINES — {len(over)}")
        for lines, path in over:
            print(f"  {lines:>5}  {path}")
        print()

    if unresolved:
        problems += len(unresolved)
        print(f"ADR CITED, NO SUCH DECISION — {len(unresolved)}")
        for number, where in sorted(unresolved.items()):
            print(f"  ADR {number}")
            for path in where[:4]:
                print(f"      {path}")
        print()

    if unrecorded:
        problems += len(unrecorded)
        print(f"QUESTION CITED, NOT IN THE REGISTER — {len(unrecorded)}")
        print("  A citation outlives the memory of the ruling. One that the")
        print("  register cannot answer for is a decision nobody wrote down.")
        for question, where in sorted(unrecorded.items()):
            print(f"  {question}")
            for path in where[:4]:
                print(f"      {path}")
        print()

    if problems == 0:
        # The clause says what the verdict measured. A bare PASS is heard as
        # *nothing is wrong anywhere*, which is not what was walked.
        print(f"PASS — {len(files)} files within {std.HARD_LIMIT} code lines,"
              " every ADR and question citation resolving.")
        return 0

    print(f"FAILED — {problems} finding(s).")
    return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv))
