using System.Text.Json;
using System.Text.RegularExpressions;
using HotelOS.Platform;
using HotelOS.RoomCare.Module.Capabilities;
using Xunit;

namespace HotelOS.RoomCare.Tests;

/// <summary>
/// Room Care works in the property's time zone (owner instruction, 2026-09-19): "today" comes from the property's
/// calendar, and a wall-clock time becomes an instant only through the property's zone — never as UTC, never as
/// the server's own zone. Workforce's b5c5ffc is the reference, where a 07:00 shift announced itself at 12:30.
/// </summary>
/// <remarks>
/// The guard reads every source file under <c>backend/src</c>, derived and never listed, and refuses the two bad
/// shapes by what the code calls. Each rule's allowance names the one file where the shape is the mechanism rather
/// than the fault, and the reason. A positive control plants each shape so a clean run is not a blind one.
/// </remarks>
public sealed class ClockShapeTests
{
    private static readonly string Source = Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", "src"));

    /// <summary>The refused shapes: what each is, the pattern, and the files where it is the mechanism itself.</summary>
    private static readonly (string What, Regex Shape, string[] Allowed)[] Rules =
    [
        ("a day taken from the UTC clock — .UtcDateTime turns an instant into UTC's wall clock", new(@"\.UtcDateTime\b"), []),
        ("the machine's clock — read it through TimeProvider, which a test can hold still", new(@"\bDateTime(Offset)?\.(Now|UtcNow|Today)\b"), []),
        ("a wall-clock time declared UTC", new(@"SpecifyKind\s*\(|DateTimeKind\.Utc"), []),
        ("a wall-clock time made an instant at offset zero", new(@"new\s+DateTimeOffset\s*\([^;]*TimeSpan\.Zero"), []),
        ("an instant made from a wall-clock time outside the property's calendar", new(@"new\s+DateTimeOffset\s*\("), ["Domain/OperatingDay.cs"]),
        ("a calendar day or time of day taken outside the property's calendar", new(@"\b(DateOnly|TimeOnly)\.FromDateTime\s*\("),
            ["Domain/OperatingDay.cs", "Application/Days/PropertyClock.cs"]),
        ("an instant parsed without requiring its offset — a bare time would be read in the server's zone",
            new(@"\bDateTimeOffset\.(Try)?Parse\s*\("), ["Module/Capabilities/TimeAndListParameters.cs"]),
        // Found after the sweep, by HH's refusal-words rule: "not before {at:HH:mm} UTC" in a refusal and in a room's
        // history. An instant formatted in its own offset and labelled UTC is a time a person reads in the wrong zone.
        ("an instant formatted as a time of day in words — say it in the property's time", new(@"\{[^}""]*:HH"), []),
        ("a time said to a person in UTC", new(@"""[^""]*\bUTC\b[^""]*"""), []),
    ];

    private static IEnumerable<string> Hits(string relative, string text) =>
        from rule in Rules
        where !rule.Allowed.Contains(relative)
        from line in text.Split('\n').Select((body, i) => (Body: body, Number: i + 1))
        let code = line.Body.TrimStart()
        where !code.StartsWith("//", StringComparison.Ordinal) && !code.StartsWith("///", StringComparison.Ordinal)
        where rule.Shape.IsMatch(line.Body)
        select $"{relative}:{line.Number} :: {rule.What}";

    [Fact]
    public void No_source_file_takes_today_from_UTC_or_treats_a_wall_clock_time_as_UTC()
    {
        var files = Directory.EnumerateFiles(Source, "*.cs", SearchOption.AllDirectories)
            .Where(f => !f.Contains($"{Path.DirectorySeparatorChar}bin{Path.DirectorySeparatorChar}") && !f.Contains($"{Path.DirectorySeparatorChar}obj{Path.DirectorySeparatorChar}")
                        && !f.Contains($"{Path.DirectorySeparatorChar}Migrations{Path.DirectorySeparatorChar}"))
            .ToList();
        // 90 files on 2026-09-19. Migrations are left out: generated by EF, their snapshots write DateTimeOffset literals.
        Assert.True(files.Count >= 80, $"the guard found {files.Count} source files under {Source}; it is not reading the backend");

        var found = files.SelectMany(f => Hits(Path.GetRelativePath(Source, f).Replace('\\', '/'), File.ReadAllText(f))).ToList();
        Assert.Empty(found);
    }

    [Fact]
    public void Each_allowance_is_still_where_the_mechanism_lives()
    {
        // An allowance for a file that no longer holds the shape is an exemption nobody is using; it goes.
        foreach (var (what, shape, allowed) in Rules)
        {
            foreach (var file in allowed)
            {
                Assert.True(shape.IsMatch(File.ReadAllText(Path.Combine(Source, file))), $"{file} no longer holds {what}; remove its allowance");
            }
        }
    }

    [Fact]
    public void The_guard_refuses_each_shape_it_names()
    {
        var planted = string.Join('\n',
            "var day = DateOnly.FromDateTime(set.UtcDateTime);",
            "var now = DateTime.UtcNow;",
            "var at = DateTime.SpecifyKind(local, DateTimeKind.Utc);",
            "var shift = new DateTimeOffset(date.ToDateTime(time), TimeSpan.Zero);",
            "var parsed = DateTimeOffset.Parse(text);",
            "var said = $\"not before {at:HH:mm}\";",
            "var label = \"at 09:00 UTC\";");
        var hits = Hits("Planted.cs", planted).Select(h => h.Split(" :: ")[1]).Distinct().ToList();
        Assert.Equal(Rules.Select(r => r.What), hits);
    }

    [Theory]
    [InlineData("2026-09-20T14:00")]
    [InlineData("2026-09-20T14:00:00")]
    public void An_instant_without_its_offset_is_refused_rather_than_read_in_the_servers_zone(string bare)
    {
        JsonElement? body = JsonDocument.Parse($"{{\"notBefore\":\"{bare}\"}}").RootElement;
        var refused = Assert.Throws<InvalidRequestException>(() => body.Instant("notBefore"));
        Assert.Equal(ModuleParameters.Unreadable, refused.Message);
    }

    [Theory]
    [InlineData("2026-09-20T14:00:00+05:30", "2026-09-20T08:30:00Z")]
    [InlineData("2026-09-20T14:00:00-06:00", "2026-09-20T20:00:00Z")]
    [InlineData("2026-09-20T08:30:00Z", "2026-09-20T08:30:00Z")]
    public void An_instant_with_its_offset_is_that_instant_in_Kolkata_Guatemala_or_UTC(string sent, string utc)
    {
        JsonElement? body = JsonDocument.Parse($"{{\"notBefore\":\"{sent}\"}}").RootElement;
        Assert.Equal(DateTimeOffset.Parse(utc, System.Globalization.CultureInfo.InvariantCulture), body.Instant("notBefore"));
    }
}
